### ISSUE TITLE
Generator function only display once in call stack when user call it circularly.

### ISSUE THREAD

**Issue by EyelynSu** [naver/pinpoint-c-agent#100]
[env]
pinpoint-c-agent: [dev-2](https://github.com/naver/pinpoint-c-agent/tree/dev-2)

[step]
1. Monitor a generator function: 
```
class TestGenerator
{
    function generator($start, $limit, $step=1){
        if($start > $limit){
            throw new LogicException("start cannot bigger that limit.");
        }
        usleep(120000);
        for($i = $start; $i<=$limit; $i += $step){
            try{
                yield $i;
            }catch (Exception $exception){
                echo $exception->getMessage();
            }
        }
    }
}
```
```
$instance = new TestGenerator();
foreach ($instance->generator(1, 10, 2) as $number){echo $number;}
```
[result]
Generator function only display once in call stack.
![1565769771](https://user-images.githubusercontent.com/41946743/63004476-1441ff80-bead-11e9-9e3a-96eb878f5351.png)

**Comment by eeliu** [comment]
@EyelynSu 
The aop not support return a wrapped gernerator.
We could add a plugin example to wrapped the return. 
Thanks

**Comment by eeliu** [comment]
Already Done! 

> since v0.2.3

## How to use

https://github.com/naver/pinpoint-c-agent/blob/v0.2.3/DOC/PHP/User%20Manual.md#221-hook-a-generator

## Example 

https://github.com/naver/pinpoint-c-agent/blob/v0.2.3/PHP/pinpoint_php_example/Plugins/GeneratorPlugin.php
