### ISSUE TITLE
When there are errors or exceptions, the request may be delayed a long time send to collector server.(apache event mode).

### ISSUE THREAD

**Issue by EyelynSu** [naver/pinpoint-c-agent#101]
[env]
pinpoint-c-agent: [dev-2](https://github.com/naver/pinpoint-c-agent/tree/dev-2)
Apache: Apache/2.4.34

[step]
1. Build php with zts.
2. Apache use event mode.
3. Send request which will return error.

[result]
The request may be delayed a long time send to collector server

**Comment by eeliu** [comment]
First of all, the error message will not missing, as it could transfer to collector-agent when this thread/process parses the next request.
Honestly to say, this is a trade off when we support workerman or swoole framework
