### ISSUE TITLE
Error when monitor Mysqli::poll.

### ISSUE THREAD

**Issue by EyelynSu** [naver/pinpoint-c-agent#102]
[env]
pinpoint-c-agent: [dev-2](https://github.com/naver/pinpoint-c-agent/tree/dev-2)

[step]
1. Monitor Mysqli::poll.

[result]
```
Warning: Declaration of app\Foo\mysqli::poll(array &$read, array &$write, array &$error, $sec, $usec = NULL) should be compatible with mysqli::poll(?array &$read, ?array &$write, ?array &$error, $sec, $usec = NULL)
```

**Comment by eeliu** [comment]
> Reason

The AOP library vis reflection for built-in, while this API was very special.
https://www.php.net/manual/en/mysqli.poll.php

If you want to trace it, a better way is wapper the mysqli::poll or replace it with mysqli_poll, they are equal.

**Comment by eeliu** [comment]
Check the `https://github.com/pinpoint-apm/pinpoint-php-aop/tree/v2.0.0-release`. 
Example, goto https://github.com/pinpoint-apm/pinpoint-c-agent/tree/Release-v4.0.0/plugins/PHP/Plugins/Sys
