### ISSUE TITLE
Exception Handling and Symphony

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint-c-agent#11]
Hi. 

I deployed php agent on a Symphony application.

It would be great to have backtrace when exception occurs in complement of Exception instantiation:

![image](https://user-images.githubusercontent.com/561441/44650659-7fb66700-a9e7-11e8-996e-90e0e8a40a72.png)

![image](https://user-images.githubusercontent.com/561441/44650528-2a7a5580-a9e7-11e8-954e-e44bde76ed89.png)

Thanks.
Olivier

**Comment by eeliu** [comment]
Thanks for your comments.


Pinpoint distinguishs this scene with color

> Fatal Error Exception (Red)

![default](https://user-images.githubusercontent.com/27064129/44970837-f7573980-af85-11e8-8d43-998c98afe427.png)

AND 

![default](https://user-images.githubusercontent.com/27064129/44971499-5fa71a80-af88-11e8-9be9-1a6e596aefe7.png)


> Catched Exception (Green)

![default](https://user-images.githubusercontent.com/27064129/44971437-24a4e700-af88-11e8-8bcc-916d5694076c.png)

**Comment by ofauchon** [comment]
Thanks for the informations .
Olivier
