### ISSUE TITLE
'LOG_DEBUG' was not declared in this scope

### ISSUE THREAD

**Issue by jefry86** [naver/pinpoint-c-agent#117]
/root/pinpoint-c-agent/PHP/pinpoint_php_ext/pinpoint_php.cpp: In function 'int pp_trace(const char*, ...)':
/root/pinpoint-c-agent/PHP/pinpoint_php_ext/pinpoint_php.cpp:722:52: error: 'LOG_DEBUG' was not declared in this scope
     php_log_err_with_severity(&PPG(logBuffer)[0] , LOG_DEBUG);
                                                    ^
/root/pinpoint-c-agent/PHP/pinpoint_php_ext/pinpoint_php.cpp:722:61: error: 'php_log_err_with_severity' was not declared in this scope
     php_log_err_with_severity(&PPG(logBuffer)[0] , LOG_DEBUG);
                                                             ^
make: *** [pinpoint_php.lo] Error 1

php version: PHP 7.0.29 (cli) (built: May  8 2018 18:33:15) ( NTS )

**Comment by eeliu** [comment]
which php version you used?

**Comment by jefry86** [comment]
> which php version you used? php 7.0.x

 PHP 7.0.29

CentOS  7.2.1511

**Comment by eeliu** [comment]
@jefry86  PHP 7.0.x not support this version.  you'd better update it to php 7.1

**Comment by jefry86** [comment]
> @jefry86 PHP 7.0.x not support this version. you'd better update it to php 7.1

Thank you. I'll try
