### ISSUE TITLE
Why only display one application, no user access information

### ISSUE THREAD

**Issue by lpvus** [naver/pinpoint-c-agent#118]
##Why only display one application, no user access information? V0.2.0
Request http://localhost:80/ through your browser
log info
``
==> collector.agent.log <==
[2019-08-19 19:37:35,984] [WARNING] [run.py:47] collector agent exit with SIGNAL
[2019-08-19 20:30:25,587] [INFO] [StreamClientLayer.py:124] try to connect:('10.66.14.67', 9994) with timeout:5
[2019-08-19 20:30:25,588] [INFO] [StreamClientLayer.py:71] connect peer: [10.66.14.67:9994] success

==> php.agent.log <==

The PinPoint dashboard displays no data

**Comment by eeliu** [comment]
hi, you should check below points 

1. Did the pinpoint_php.so included?
2. Did the vendor/autoload.php had replaced with the auto_pinpointed.php?

For 2, you can find a our Guide PHP project under https://github.com/naver/pinpoint-c-agent/tree/master/PHP/pinpoint_php_example.
Hope to help you

**Comment by lpvus** [comment]
1.[work@phpsit2 ~]$ php -m | grep pinpoint
pinpoint_php

2.pinpoint_php_example/index.php  Already introduced file “auto_pinpointed.php”
`define('AUTOLOAD_FILE_ALIAS',__DIR__."/../vendor/autoload.php");
define('AOP_CACHE_DIR',__DIR__.'/../Cache/');
define('PLUGINS_DIR',__DIR__.'/../Plugins/');
require_once __DIR__. '/../vendor/eeliu/php_simple_aop/auto_pinpointed.php';
require_once __DIR__.'/Args.php';`

3.Plugins/PreRequestPlugin.php 
This file has been executed.
I'm trying to print  `var_dump(pinpoint_add_clues(HTTP_STATUS_CODE,http_response_code())); return NULL`
==> php.agent.log <==   Still no log information is output

4.My other configuration information
1）php.ini
> extension=pinpoint_php.so
pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0 # 0 is recommanded
pinpoint_php.TraceLimit=-1

2)collector.conf

> [Collector]
AgentID=dev
ApplicationName=dev-app
CollectorSpanIp=10.66.14.67
CollectorSpanPort=9996
CollectorStatIp=10.66.14.67
CollectorStatPort=9995
CollectorTcpIp=10.66.14.67
CollectorTcpPort=9994
[Common]
Web_Port=80  
Log_Level=INFO
LOG_DIR=/tmp/
[Agent]
Address=/tmp/collector-agent.sock

3)php version

> [work@phpsit2 conf]$ php -v
PHP 7.2.0 (cli) (built: Dec 27 2017 09:04:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.2.0, Copyright (c) 1999-2017, by Zend Technologies


I really don't know what the problem is. I need your help ！
If you have WeChat or QQ, you can contact me to help me check, I will thank you very much

**Comment by eeliu** [comment]
> 1.[work@phpsit2 ~]$ php -m | grep pinpoint
> pinpoint_php
> 
> 2.pinpoint_php_example/index.php Already introduced file “auto_pinpointed.php”
> `define('AUTOLOAD_FILE_ALIAS',__DIR__."/../vendor/autoload.php"); define('AOP_CACHE_DIR',__DIR__.'/../Cache/'); define('PLUGINS_DIR',__DIR__.'/../Plugins/'); require_once __DIR__. '/../vendor/eeliu/php_simple_aop/auto_pinpointed.php'; require_once __DIR__.'/Args.php';`
> 
> 3.Plugins/PreRequestPlugin.php
> This file has been executed.
> I'm trying to print `var_dump(pinpoint_add_clues(HTTP_STATUS_CODE,http_response_code())); return NULL`
> ==> php.agent.log <== Still no log information is output
> 
> 4.My other configuration information
> 1）php.ini
> 
> > extension=pinpoint_php.so
> > pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
> > pinpoint_php.SendSpanTimeOutMs=0 # 0 is recommanded
> > pinpoint_php.TraceLimit=-1
> 
> 2)collector.conf
> 
> > [Collector]
> > AgentID=dev
> > ApplicationName=dev-app
> > CollectorSpanIp=10.66.14.67
> > CollectorSpanPort=9996
> > CollectorStatIp=10.66.14.67
> > CollectorStatPort=9995
> > CollectorTcpIp=10.66.14.67
> > CollectorTcpPort=9994
> > [Common]
> > Web_Port=80
> > Log_Level=DEBUG
> > LOG_DIR=/tmp/
> > [Agent]
> > Address=/tmp/collector-agent.sock
> 
> 3)php version
> 
> > [work@phpsit2 conf]$ php -v
> > PHP 7.2.0 (cli) (built: Dec 27 2017 09:04:38) ( NTS )
> > Copyright (c) 1997-2017 The PHP Group
> > Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
> > with Zend OPcache v7.2.0, Copyright (c) 1999-2017, by Zend Technologies
> 
> I really don't know what the problem is. I need your help ！
> If you have WeChat or QQ, you can contact me to help me check, I will thank you very much

From the configuration your provide, every things is OK.

While, your " http://localhost:80/ ", did this will call a php script ?

1. The pinpoint-php-agent, only hooks the php script file !
2.  You should check the auto_load.php (vendor/auto_load.php) is disable.  [Some example](https://github.com/eeliu/php_simple_aop/blob/master/Readme.md#activate-plugins)
