### ISSUE TITLE
curl_plugin not showing details

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint-c-agent#12]
curl_exec_interceptor do not send called URL on pinpoint web: 

![image](https://user-images.githubusercontent.com/561441/44662302-b3a48300-aa0d-11e8-9347-ab0602efde57.png)

**Comment by eeliu** [comment]
This feature had added.

> pinpoint call stack 

![default](https://user-images.githubusercontent.com/27064129/44966541-65900200-af6e-11e8-8d66-b7528fd4bde6.png)

> code changes

https://github.com/naver/pinpoint-c-agent/pull/14/commits/1acf5fec7ef0949efd7622a7c44bca97d4d26ae1#r214570622
