### ISSUE TITLE
run pinpoint_php_demo something wrong!

### ISSUE THREAD

**Issue by yelstr** [naver/pinpoint-c-agent#121]
Call to a member function getComments() on null/home/work/lxf/pinpoint-c-agent/PHP/pinpoint_php_example/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php
the extension pinpoint_php is installed,but the demo can't run in the right way.
Thank you very much for helping me solve this problem.

**Comment by eeliu** [comment]
@yelstr 
Could you give the full stack and your PHP script, it looks bad!

**Comment by yelstr** [comment]
@eeliu 我这边找到失败原因了，我的php缺少redis和mysql配置。但是demo正常运行了，数据还是没有收集上去。

**Comment by eeliu** [comment]
@yelstr 

If you need more help, you can join all QQ group.
But now I close this issue.
