### ISSUE TITLE
How often does collector agent report? Can this time be adjusted?

### ISSUE THREAD

**Issue by lpvus** [naver/pinpoint-c-agent#125]
1.How often does collector agent report? Can this time be adjusted?

>   1 second? 10 seconds? 1 minute?

2.Is redis plug-in to be developed by yourself?

3.pinpoint_php.TraceLimit=x  Parameter specification?

**Comment by eeliu** [comment]
> A1

collector agent will pass the span as quickly as possible ! NO limitation.
while, except this https://github.com/naver/pinpoint-c-agent/issues/101.

> A2

v0.2.0 just support it to capture it. https://github.com/naver/pinpoint-c-agent#todo
While you can help us.

>A3

Number of requests in 1 sec. 
```
# request should be captured duing 1 second. < 0 means no limited
pinpoint_php.TraceLimit=-1 
```

**Comment by lpvus** [comment]
I'm writing a plugin for mysql. What is the STP value? Which parameters also need to be matched
`PluginsDefines.php`
I've only seen the definitions of Redis, Memcached, PHP. Is there any documentation?
> define('PHP_ARGS',-1);
define('PHP_RETURN',14);
define('PROXY_HTTP_HEADER',300);
define('SQL_ID' ,20);
define("SQL",  21);
define("SQL_METADATA",  22);
define("SQL_PARAM",  23);
define("SQL_BINDVALUE",  24);
define("STRING_ID", 30);
define("HTTP_URL", 40);
define("HTTP_PARAM",  41);
define("HTTP_PARAM_ENTITY",  42);
define("HTTP_COOKIE",  45);
define("HTTP_STATUS_CODE",  46);
define("HTTP_INTERNAL_DISPLAY",  48);
define("HTTP_IO",  49);
define("MESSAGE_QUEUE_URI ",100);
define("PHP_METHOD","1501");
define("PHP","1500");
define("REDIS","8200");
define("MEMCACHED","8050");
define("PINPOINT_PHP_REMOTE",9700);
define("NGINX_PROXY","Pinpoint-ProxyNginx");
define("APACHE_PROXY","HTTP_PINPOINT_PROXYAPACHE");
define("SAMPLED","Pinpoint-Sampled");

**Comment by eeliu** [comment]
@Ipvus
 hi, pls check this 

https://github.com/naver/pinpoint-c-agent/blob/master/collector-agent/TCollectorAgent/Readme.md

Thanks you so much !
