### ISSUE TITLE
why my pinpoint-agent install in php7.1 is not work？

### ISSUE THREAD

**Issue by xingliguang** [naver/pinpoint-c-agent#126]
Centos 7.6  x86_64
Python:  Python 3.6
gcc version 4.8.5
pinpoint web + pinpoint col : 1.8.4     IP 172.16.100.201
###
install by     https://github.com/naver/pinpoint-c-agent 
php  web  messages:
ip 172.16.100.202     
php    PHP 7.1.28 

log:
cat /var/log/php-pinpoint.logcollector.agent.log 
[2019-08-21 11:12:37,580] [INFO] [StreamClientLayer.py:124] try to connect:('172.16.100.201', 9994) with timeout:5
[2019-08-21 11:12:37,581] [INFO] [StreamClientLayer.py:71] connect peer: [172.16.100.201:9994] success
socket:
ls  /tmp/collector-agent.sock

collector.conf 
[Collector]
AgentID=devphp
ApplicationName=devphp-app
CollectorSpanIp=172.16.100.201
CollectorSpanPort=9996
CollectorStatIp=172.16.100.201
CollectorStatPort=9995
CollectorTcpIp=172.16.100.201
CollectorTcpPort=9994
[Common]
# your web server (nginx&apache) port
Web_Port=80      ####nginx port  
# debug in dev 
Log_Level=INFO
LOG_DIR=/var/log/php-pinpoint.log
[Agent]
# the same as below "pinpoint_php.CollectorHost"
Address=/tmp/collector-agent.sock

test  url 
http://172.16.100.202    
result:
not supported type

**Comment by eeliu** [comment]
@xingliguang 

pls check the index.php. It's easy.

**Comment by xingliguang** [comment]
@eeliu  sorry  ,i don't  know how to check
the  file of index.php  last  line is:
    default:
        echo "not supported type $type";
}

**Comment by eeliu** [comment]
@xingliguang 

https://github.com/naver/pinpoint-c-agent/blob/master/PHP/pinpoint_php_example/app/index.html

**Comment by xingliguang** [comment]
I want to monitor the PHP log in the LNMP architecture through PinPoint. However, according to the https://github.com/naver/pinpoint-c-agent link, the http://172.16.100.201:28080 interface does not see the log.

**Comment by eeliu** [comment]
Check this issue https://github.com/naver/pinpoint-c-agent/issues/124.  it maybe help you

**Comment by xingliguang** [comment]
Thanks,I have seen it, (#124)  but it didn't help.


------------------ 原始邮件 ------------------
发件人: "eeliu"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 下午3:10
收件人: "naver/pinpoint-c-agent"<pinpoint-c-agent@noreply.github.com>;
抄送: "流年似水"<2587119527@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [naver/pinpoint-c-agent] why my pinpoint-agent install in php7.1 is not work？ (#126)




Check this issue #124.  it maybe help you

**Comment by eeliu** [comment]
1.access the index.html
2. post the output to us. 

it's convenient to us if you record a gif or video to show the problems.

**Comment by xingliguang** [comment]
Hello, the two pictures attached are the display contents of the LNMP server access index.html.










------------------ 原始邮件 ------------------
发件人: "eeliu"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 晚上10:24
收件人: "naver/pinpoint-c-agent"<pinpoint-c-agent@noreply.github.com>; 
抄送: "流年似水"<2587119527@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [naver/pinpoint-c-agent] why my pinpoint-agent install in php7.1 is not work？ (#126)




1.access the index.html
 2. post the output to us.
 
it's convenient to us if you record a gif or video to show the problems.

**Comment by eeliu** [comment]
@xingliguang 

Where is your attachment ?

**Comment by xingliguang** [comment]
sorry, my fault, The previous attachment was not added successfully。 here is:
![pinpoint1](https://user-images.githubusercontent.com/24713062/63666793-e68d7c80-c803-11e9-9536-5e1faa4a440d.jpg)

![pinpoint2](https://user-images.githubusercontent.com/24713062/63666814-f60cc580-c803-11e9-8169-809e2993a1ae.jpg)

**Comment by eeliu** [comment]
This url works fine, post the response when click 
![image](https://user-images.githubusercontent.com/27064129/63667929-0e7edf00-c808-11e9-95f2-579b7cbc3b34.png)

**Comment by xingliguang** [comment]
Yes, I clicked the button on the page and the message popped up, but the http://172.16.100.201:28080 interface still has no data.

![pinpoint3](https://user-images.githubusercontent.com/24713062/63675475-7be83b00-c81b-11e9-96a8-33ccb1b1ca60.jpg)

![pinpoint4](https://user-images.githubusercontent.com/24713062/63675490-830f4900-c81b-11e9-82b5-27f994c3a1c5.jpg)

**Comment by eeliu** [comment]
goto https://github.com/naver/pinpoint-c-agent/issues/122#issuecomment-522907225

It looks your agent is works! 

while, post the log files(collector agent and php error log) to us.

**Comment by xingliguang** [comment]
my php.ini 

log_errors = On
error_log = "/opt/logs/php7.1/php.error.log"
………………
[pinpoint]
extension = pinpoint_php.so
pinpoint_php.CollectorHost=/tmp/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0
pinpoint_php.TraceLimit=-1
pinpoint_php.DebugReport=true

# cat /var/log/php-pinpoint.logcollector.agent.log
[2019-08-26 16:41:10,220] [WARNING] [run.py:47] collector agent exit with SIGNAL
[2019-08-26 16:41:20,548] [INFO] [StreamClientLayer.py:124] try to connect:('172.16.100.201', 9994) with timeout:5
[2019-08-26 16:41:20,549] [INFO] [StreamClientLayer.py:71] connect peer: [172.16.100.201:9994] success
show python process：
# ps -ef |grep python
root      3648     1  0 Jul12 ?        00:08:24 /usr/bin/python2 -Es /usr/sbin/tuned -l -P
root     29235 29165  0 16:41 pts/0    00:00:00 python run.py
root     29248 29165  0 16:42 pts/0    00:00:00 grep --color=auto python

# cat collector.conf
[Collector]
AgentID=devphp
ApplicationName=devphp-app
CollectorSpanIp=172.16.100.201
CollectorSpanPort=9996
CollectorStatIp=172.16.100.201
CollectorStatPort=9995
CollectorTcpIp=172.16.100.201
CollectorTcpPort=9994
[Common]
# your web server (nginx&apache) port
Web_Port=80
# debug in dev 
Log_Level=INFO
LOG_DIR=/var/log/php-pinpoint.log
[Agent]
# the same as below "pinpoint_php.CollectorHost"
Address=/tmp/collector-agent.sock

php  error  log is empty

**Comment by eeliu** [comment]
Thanks, and this file "/opt/logs/php7.1/php.error.log", does it empty ?

**Comment by xingliguang** [comment]
yes. /opt/logs/php7.1/php.error.log  is  empty

**Comment by eeliu** [comment]
Checking your php-fpm logging, 

```
log_errors = On
error_log = "/opt/logs/php7.1/php.error.log"
```

Your  `error_log ` should not empty when "pinpoint_php.DebugReport=true". https://github.com/naver/pinpoint-c-agent/issues/126#issuecomment-524763371, looks the aop and pinpint-php is working.

**Comment by xingliguang** [comment]
sorry ,my faults .There is a problem with the php.error.log file permissions. Attachment is the php.error.log log
[php.error.log](https://github.com/naver/pinpoint-c-agent/files/3540669/php.error.log)

**Comment by eeliu** [comment]
Did you use apache+php7.so ?

**Comment by xingliguang** [comment]
# /opt/app/php7.1/bin/php -v
PHP 7.1.28 (cli) (built: Aug 19 2019 18:45:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.28, Copyright (c) 1999-2018, by Zend Technologies

# /opt/app/tengine/sbin/nginx  -v
Tengine version: Tengine/2.1.2 (nginx/1.6.2)

# ll /opt/app/php7.1/lib/php/extensions/no-debug-non-zts-20160303/
total 15272
-rwxr-xr-x 1 root root  587944 Aug 19 18:47 amqp.so
-rwxr-xr-x 1 root root  418120 Aug 19 18:47 apcu.so
-rwxr-xr-x 1 root root   48360 Aug 19 18:47 inotify.so
-rwxr-xr-x 1 root root 4715168 Aug 19 18:49 mongodb.so
-rwxr-xr-x 1 root root 3415724 Aug 19 18:46 opcache.a
-rwxr-xr-x 1 root root 1639192 Aug 19 18:46 opcache.so
-rwxr-xr-x 1 root root 2099048 Aug 20 13:29 pinpoint_php.so
-rwxr-xr-x 1 root root 2379016 Aug 19 18:49 redis.so
-rwxr-xr-x 1 root root   92168 Aug 19 18:49 yaconf.so
-rwxr-xr-x 1 root root  209192 Aug 19 18:49 yac.so

**Comment by eeliu** [comment]
@xingliguang  
Did you use the php-fpm ?

**Comment by xingliguang** [comment]
However, there is still no data ………………
![pinpoint4](https://user-images.githubusercontent.com/24713062/63685708-a5f92780-c832-11e9-90fa-e12cb1a73fa9.jpg)

**Comment by eeliu** [comment]
@xingliguang 
There is a handshake process in each PHP kernel  when start.

> Give us the php.error.log 

For php-fpm,
1. Start with 2 worker process
2. Request about 10 times
3. Post the `php.error.log` when done.

**Comment by xingliguang** [comment]
ok，php.error.log
[php.error.log](https://github.com/naver/pinpoint-c-agent/files/3544015/php.error.log)

**Comment by eeliu** [comment]
You made a mistaken:

pinpoint_php.CollectorHost=~/tmp/collector-agent.sock~    

pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock

**Comment by xingliguang** [comment]
Ok, I made a very low-level mistake. After the change, everything is normal, thank you very much。

**Comment by eeliu** [comment]
Done, I think.
