### ISSUE TITLE
Is there a plan to support yii2?

### ISSUE THREAD

**Issue by jefry86** [naver/pinpoint-c-agent#127]
Is there a plan to support yii2?

**Comment by eeliu** [comment]
@jefry86 

yii2 supports classload(composer). In other word , pinpont-php-agent  supports yii2.

While, agent does not have out-of-box plugins for yii2.

**Comment by jefry86** [comment]
> @jefry86
> 
> yii2 supports classload(composer). In other word , pinpont-php-agent supports yii2.
> 
> While, agent does not have out-of-box plugins for yii2.

Do you have plans to develop out-of-box plugins for yii2?

**Comment by eeliu** [comment]
OK, let me do some research !

**Comment by eeliu** [comment]
It's done. 
Use v0.2.3
