### ISSUE TITLE
Build php-agend for php 7.2.7

### ISSUE THREAD

**Issue by shiyapeng** [naver/pinpoint-c-agent#128]
I use the version 0f pinpoint-c-agent is v0.1.1rc1, the version of php is 7.2.7. when I execute the step 2 of 'Build php-agent' in README.md, it is 'Run cd pinpoint_php && ./Build.sh && sudo make install' . the error happened, help please:

/usr/local/boost.1.63//include/boost/system/error_code.hpp: At global scope:
/usr/local/boost.1.63//include/boost/system/error_code.hpp:221:36: warning: ‘boost::system::posix_category’ defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
/usr/local/boost.1.63//include/boost/system/error_code.hpp:222:36: warning: ‘boost::system::errno_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
/usr/local/boost.1.63//include/boost/system/error_code.hpp:223:36: warning: ‘boost::system::native_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();

**Comment by eeliu** [comment]
@shiyapeng 
I recommend you use the v0.2.0 (had removed boost dependency)

**Comment by shiyapeng** [comment]
> @shiyapeng
> I recommend you use the v0.2.0 (had removed boost dependency)

the v0.2.0 don't support php 5.6。 There are project of php5.6 and project of php7.2  at the same time in my Centos system，  so I use the v0.1.1rc1。

**Comment by eeliu** [comment]
One agent to one project ! 

https://github.com/naver/pinpoint-c-agent/issues/94

 v0.2.x could support one to many in future !

**Comment by shiyapeng** [comment]
> One agent to one project !
> 
> #94
> 
> v0.2.x could support one to many in future !

yes，so I install and setup two pinpoint agent in mysql Centos system , one for php5.6, one for php7.2 ,the php5.6 agent is running ,but the php7.2 agent build error.
