### ISSUE TITLE
v0.2.0 build fail with docker fpm:7.3-fpm-apline

### ISSUE THREAD

**Issue by tongv** [naver/pinpoint-c-agent#129]
g++ -I. -I/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext -DPHP_ATOM_INC -I/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/include -I/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/main -I/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/depends/json/include -DHAVE_CONFIG_H -g -O2 -c /src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/pinpoint_helper.cpp  -fPIC -DPIC -o .libs/pinpoint_helper.o
In file included from /src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/pinpoint_helper.cpp:22:
/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/pinpoint_helper.h:48:9: error: 'uint' does not name a type; did you mean 'int'?
         uint block_size;
         ^~~~
         int
/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/pinpoint_helper.h:49:9: error: 'uint' does not name a type; did you mean 'int'?
         uint l_ofs; // The continuous buffer left offset in data ***(l_ofs)--------------(r_ofs)*****
         ^~~~
         int
/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/pinpoint_helper.h:50:9: error: 'uint' does not name a type; did you mean 'int'?
         uint r_ofs; // The continuous buffer right offset in data
         ^~~~
         int
/src/pinpoint-c-agent-0.2.0/PHP/pinpoint_php_ext/pinpoint_helper.h:63:11: error: 'uint' does not name a type; did you mean 'int'?
     const uint c_resident_size;

**Does it not support this? docker image 7.3-fpm-alpine**

**Comment by eeliu** [comment]
Nice catch! 
I will check this version.

**Comment by eeliu** [comment]
Pls goto https://github.com/naver/pinpoint-c-agent/tree/v0.2.0.rc
