### ISSUE TITLE
Agent reporting "Unsupported version" in realtime view

### ISSUE THREAD

**Issue by ObiJonKenobi89** [naver/pinpoint-c-agent#133]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> Please describe the behavior you are expecting

Monitoring of PHP 7.2 

# Current Behavior

> What is the current behavior?

Agent reporting "Unsupported Version" when viewing real time monitoring

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: CentOS Linux release 7.6.1810 (Core)

* PHP Version: PHP 7.2.21 (cli) (built: Jul 30 2019 14:46:08) ( NTS )

* php.ini: 
extension=pinpoint_php.so
pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0 # 0 is recommanded
pinpoint_php.TraceLimit=-1

* php-fpm or apache: Server version: Apache/2.4.6 (CentOS)
Server built:   Jul 29 2019 17:18:49

* pinpoint_agent.conf: 
[Collector]
AgentID=SWP.Dev01
ApplicationName=SWP.Dev
CollectorSpanIp=[redacted]
CollectorSpanPort=9996
CollectorStatIp=[redacted]
CollectorStatPort=9995
CollectorTcpIp=[redacted]
CollectorTcpPort=9994
[Common]
Web_Port=8079
Log_Level=INFO
LOG_DIR=/bin/PinpointLog
[Agent]
Address=/tmp/collector-agent.sock

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )

(Where are these located? Apologies, newbie sysadmin and new to the devops side of things) 

Hi guys,

See attached image. I've followed the instructions on readme.md and I'm running PHP 7.2, GCC 12, Python 3 and Pinpoint 1.8.0 in a dockerized instance. 

Not entirely sure where to start looking first -- any hints would be much appreciated. 

Thanks in advance
![Capture](https://user-images.githubusercontent.com/54354558/63762969-b3a6bf80-c8bb-11e9-9c6c-e2ed6ca8f711.PNG)

**Comment by eeliu** [comment]
@ObiJonKenobi89
 Oh, sorry
pinpoint-php-agent not support threadump right now.

**Comment by ObiJonKenobi89** [comment]
Thanks for the response
