### ISSUE TITLE
Does the collector agent have a filter configuration?

### ISSUE THREAD

**Issue by lpvus** [naver/pinpoint-c-agent#145]
Now all the user request routing will be collected, I want to filter some routing URL, may I set it?

**Comment by eeliu** [comment]
@lpvus 

Use  `pinpoint_drop_trace` 

https://github.com/naver/pinpoint-c-agent/blob/dcf0c9aebd60894b9ce30290bfdc07f561510b71/PHP/pinpoint_php_ext/pinpoint_php_api.php#L40-L43

> Example 

https://github.com/naver/pinpoint-c-agent/blob/dcf0c9aebd60894b9ce30290bfdc07f561510b71/PHP/pinpoint_php_example/Plugins/PerRequestPlugins.php#L118-L124


By the way, v0.2.0 only supporting filter at plugins-side, not supporting at collector-agent side.
