### ISSUE TITLE
pinpoint server versions requirements

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint-c-agent#15]
Hi. 

What are the pinpoint-web/pinpoint-collector version requirements  for php plugin agent.

Maybe you could add this information on the main readme.

Thanks

**Comment by eeliu** [comment]
The pinpoint-web/pinpoint-collector  version is  [1.8.0-RC1+](https://github.com/naver/pinpoint/tree/1.8.0-RC1)
