### ISSUE TITLE
Build failed on the macOS (combine declaration issue)

### ISSUE THREAD

**Issue by decorus-kazuma** [naver/pinpoint-c-agent#157]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior
Build complete.

# Current Behavior
Build failed.

I found #130 pr related to this issue.
On a Mac, the following error occurs:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/types.h:92:33: error: 
      cannot combine with previous 'int' declaration specifier
typedef unsigned int            uint;           /* Sys V compatibility */
                                ^
./common.h:23:23: note: expanded from macro 'uint'
#define uint unsigned int
                      ^
1 warning and 1 error generated.
make: *** [pinpoint_helper.lo] Error 1
```
After removing the #define part, I changed the declaration to the typedef. 
```cpp
#ifndef uint
typedef unsigned int uint;
#endif
```
It works fine on a mac.

**Comment by eeliu** [comment]
@decorus-kazuma 

It's a nice change  for support for macOS. 

Thanks your response!
