### ISSUE TITLE
Precisiond for addInterceptor / addSimpleInterceptor usage.

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint-c-agent#19]
Hi. 

I plan do code a simple interceptor to trace SQL Queries from Symphony/Doctrine/PDO/Mysql. 

I read the API documentation (https://github.com/naver/pinpoint-c-agent/wiki/pinpoint-agent-php-api) 

![image](https://user-images.githubusercontent.com/561441/45080950-5936b100-b0f6-11e8-8387-962cfde610b0.png)

and the examples, but i'm still not sure how to register these methods: 

  - http://php.net/manual/fr/pdo.query.php
  - http://php.net/manual/fr/mysqli.query.php

What is the correct syntax addInterceptor/addSimpleInterceptor so it match the above methods ?

Thanks 
Olivier Fauchon

**Comment by eeliu** [comment]
There are some examples in "https://github.com/naver/pinpoint-c-agent/tree/dev/simulate/web/php/plugins", hope it would help you.

> Note

  "plugins_create.php" is the entry of the plugin

**Comment by kdszh** [comment]
Hi, @ofauchon   , I plan to  do interceptor to trace SQL Queries in Laravel , like:  DB::select，do you have some code example now ?

**Comment by ofauchon** [comment]
Hi kdszh, 

I did not manage to write an interceptor for mysql queries at the moment. 

Sorry.
Olivier

**Comment by eeliu** [comment]
@ofauchon  @kdszh 

### Example 

> dst code 

https://github.com/naver/pinpoint-c-agent/blob/eb0865db27c0d365485d3102f58f114382741c11/simulate/web/php/test_mysql.php#L37

> Plugins example

   $this->addSimpleInterceptor("PDO::query", -1);


![default](https://user-images.githubusercontent.com/27064129/46193776-dfc76280-c331-11e8-9088-1ea7a8ba41fc.png)

**BUT**

If you want get specify the return format , try to write you own interceptor like this.

https://github.com/naver/pinpoint-c-agent/blob/eb0865db27c0d365485d3102f58f114382741c11/simulate/web/php/plugins/test_plugin.php#L44-L59

**Comment by kdszh** [comment]
Yeap .. in my laravel stack, code like these:

> Example

`    $i = new MysqlInterceptor();
    $this->addInterceptor($i, "Illuminate\\Database\\Connection::select", "quickstart_plugin.php");
`

>  Or

`    
$this->addSimpleInterceptor("Illuminate\\Database\\Connection::select", -1);
`

it works.

**Comment by ofauchon** [comment]
Hi.
Thanks for the informations.

Please find above a nice piece of php to list all namespaces/classes/methods.

That can help for interceptor implementations :

`<?php  
$classes = get_declared_classes();
foreach ($classes as $cl){  
 echo "$cl\n";
  $methods = get_class_methods($cl);
  foreach ($methods as $me){
  echo "    - $me\n";
  }
}`

**Comment by eeliu** [comment]
Done
