### ISSUE TITLE
Valid workflows of internal pinpoint key for clue/clues function

### ISSUE THREAD

**Issue by ladriandan** [naver/pinpoint-c-agent#195]
Hello,

Is there a guide of what key you can use in pinpoint_add_clue/pinpoint_add_clues functions and the correct order to use them after you start a trace?

Best regards,
Thank you.

**Comment by EyelynSu** [comment]
Hello~
Please ref to https://github.com/naver/pinpoint-c-agent/blob/master/collector-agent/CollectorAgent/Readme.md, hope it help.

**Comment by ladriandan** [comment]
Hi,

The order doesn't matter?

Best regards.

**Comment by eeliu** [comment]
@ladriandan 
Yes, but all clue/clues must be setting after you start a trace and before end a trace.

**Comment by ladriandan** [comment]
ok, thx.
