### ISSUE TITLE
No valid stp for SQL in PluginDefines.php

### ISSUE THREAD

**Issue by ladriandan** [naver/pinpoint-c-agent#196]
I can not mark a database as SQL Server with "pinpoint_add_clue("stp",SQL)" maybe that is not the scope of that defined,
I'm getting an UNKNOWN value in web-ui but for MYSQL it works fine with "pinpoint_add_clue("stp",MYSQL)"

Do you have a list of valid stp values that can be used or how can we add new valid values?

**Comment by EyelynSu** [comment]
Hello~
Below is the list of "stp":
https://github.com/naver/pinpoint/blob/master/commons/src/main/java/com/navercorp/pinpoint/common/trace/ServiceType.java

**Comment by ladriandan** [comment]
Hi,

I've change the type from MYSQL to MSSQL and in the inspector it is show as MSSQL but in the graphic part in the web-ui it no longer appears as a separate circle like the MYSQL.

**Comment by EyelynSu** [comment]
@ladriandan 
Write you own MSSQL plugin which add `pinpoint_add_clue("stp", "2201");` under `Plugin` directory, and monitor the MSSQL functions in your MSSQL plugin.
PHP example ref to https://github.com/naver/pinpoint-c-agent/blob/master/Example/PHP/Plugins/PDOCommonPlugin.php
![1594805264](https://user-images.githubusercontent.com/41946743/87529609-d3a4c480-c6c1-11ea-8f08-c54a0162562c.png)

**Comment by ladriandan** [comment]
Hi,

Done and it works.

The problem was in the PluginsDefines.php that the MYSQL was defined with the value 2101 and in the link of service type you send me MYSQL is defined as 2100. So I expected that MSSQL would be 2200 as in de link but it's not the MSSQL that I have to use it's the MSSQL_EXECUTE_QUERY and in  PluginsDefines.php should be MYSQL_EXECUTE_QUERY.
