### ISSUE TITLE
List of available key to use in pinpoint_add_clue/pinpoint_add_clues

### ISSUE THREAD

**Issue by ladriandan** [naver/pinpoint-c-agent#197]
Hi,

Is there a list of available key to use in the functions pinpoint_add_clue and pinpoint_add_clues?

Can we add custome ones?

Thank you.

**Comment by EyelynSu** [comment]
Hello~
Please ref to https://github.com/naver/pinpoint-c-agent/blob/master/collector-agent/CollectorAgent/Readme.md, hope it help.
Custome ones not support now.

**Comment by ladriandan** [comment]
Hi,

Yes that was what I wanted it's just that it says that is for trift and I'm using grpc. Do they use the same keys?

By the way in a lot of plugins in the "PHP Excample" you are using the 'EXP' key for exceptions not the 'ER' + 'EMSG' so that make me believe that this list in not updated as the 'EXP' key it's not in that list. Are there any more keys beside EXP that are missing from the documentation?

What type of data can you send in each key, ex: int|float|string?
What limitation are applied over the data that you can send in each key, or there is none, ex: length|no negative|etc...? 
For 'stp' you have pointed me to the valid list to use in the #196 does a list like that exists for any other key?

Best regards,
Thank you.

**Comment by eeliu** [comment]
> "Yes that was what I wanted it's just that it says that is for trift and I'm using grpc. Do they use the same keys?"

the same

> What type of data can you send in each key, ex: int|float|string?

Only support string.

>What limitation  ...

Try to make agent simple and easy.

**Comment by ladriandan** [comment]
> By the way in a lot of plugins in the "PHP Excample" you are using the 'EXP' key for exceptions not the 'ER' + 'EMSG' so that make me believe that this list in not updated as the 'EXP' key it's not in that list. Are there any more keys beside EXP that are missing from the documentation?

About this ?

**Comment by ladriandan** [comment]
I'm closing this issue as the initial scope is reached.
