### ISSUE TITLE
pinpoint web - Response Summary & Load chart is empty 

### ISSUE THREAD

**Issue by kdszh** [naver/pinpoint-c-agent#21]
Hello,  my pinpint-c-agent works in "nginx+php-fpm" stack,but pinpoint web only show access point data, the Response Summary & Load chart is empty , help
![pp](https://user-images.githubusercontent.com/2100801/45209029-8cc43780-b2be-11e8-9e81-430a578c3ccc.png)

**Comment by EyelynSu** [comment]
In our test env, there is no such problem.
![1536311127](https://user-images.githubusercontent.com/41946743/45209723-41ab2400-b2c0-11e8-8392-f01a384ac46e.png)
Could you please give us more infomations, such as logs(both pinpoint-web and pinpoint-agent), so that we can trace the problem. Thanks!

**Comment by ChenGXQQ** [comment]
Please give us the logs of pinpoint-collector and pinpoint-web too.

**Comment by kdszh** [comment]
here comes the logs:
[pinpoint-col.log](https://github.com/naver/pinpoint-c-agent/files/2369307/pinpoint-col.log)
[pinpoint-web.log](https://github.com/naver/pinpoint-c-agent/files/2369308/pinpoint-web.log)

**Comment by ChenGXQQ** [comment]
@emeroad Please help us to analyze

**Comment by ChenGXQQ** [comment]
I find some zookeeper's error in your collector's log. Though I am not sure that it is the reason, I think it is better to fix them firstly.
Furthermore, I notice your collector is 1.7.3. 1.8.0 is more supportive for PHP agent. I recommand highly you use 1.8.0+.

![default](https://user-images.githubusercontent.com/20234781/45346735-a75b2100-b5dc-11e8-8e6a-f603d8464b20.png)
![default](https://user-images.githubusercontent.com/20234781/45346831-f739e800-b5dc-11e8-9580-86a19fa5b59b.png)

**Comment by ChenGXQQ** [comment]
I guess the most possible reason is that there is dirty data in your HBase. If it is not your product env, it is worth to try to re-install your HBase.

**Comment by kdszh** [comment]
the reason is HBase version. 
I used HBase 2.1.0 before, later I reinstalled HBase 1.2.6 and init the data table again，the problem was settled .

thanks @ChenGXQQ
