### ISSUE TITLE
proxy-http-header opption support ?

### ISSUE THREAD

**Issue by kdszh** [naver/pinpoint-c-agent#22]
Hi, does pinpint-c-agent support this opption like pinpoint-agent ?
         profiler.proxy.http.header.enable=true

refer link: 
[proxy-http-header](https://github.com/naver/pinpoint/blob/master/doc/proxy-http-header.md)

**Comment by ChenGXQQ** [comment]
Sorry, no.

**Comment by jaehong-kim** [comment]
@kdszh 
Pinpoint Web function.
It is independent of the Agent.
