### ISSUE TITLE
some problem about complie

### ISSUE THREAD

**Issue by lovexiongmao** [naver/pinpoint-c-agent#220]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> Please describe the behavior you are expecting
compile success

# Current Behavior

> What is the current behavior?
apk --update add build-base autoconf
cd pinpoint-c-agent/
/usr/local/php/bin/phpize
./configure --with-php-config=/usr/local/php/bin/php-config
make
get the following err:

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
apk --update add build-base autoconf
git clone https://github.com/naver/pinpoint-c-agent.git
cd pinpoint-c-agent/
/usr/local/php/bin/phpize
./configure --with-php-config=/usr/local/php/bin/php-config
make

## Context
I complie in a apline container

* Operating System:

* PHP Version:
7.x

* php.ini:

* php-fpm or apache:

* pinpoint_agent.conf:

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )
cc -shared  src/PHP/.libs/pinpoint_php.o  -lstdc++ -L/root/pinpoint-c-agent/common/lib -l:libpinpoint_common.a -l:libjsoncpp.a -lrt  -Wl,-soname -Wl,pinpoint_php.so -o .libs/pinpoint_php.so
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -l:libpinpoint_common.a
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -l:libjsoncpp.a
collect2: error: ld returned 1 exit status

**Comment by rocfy** [comment]
我也遇到这个问题了，有解决的吗？

**Comment by lovexiongmao** [comment]
没有啊，兄弟，一起解决把，解决了的话说一声。我解决的话，我也说一声。你直接就开始飙中文了。。。老外一脸懵

**Comment by eeliu** [comment]
Please attach the output when running `./configure`  command.

**Comment by lovexiongmao** [comment]
@eeliu here is the log of ./configure
`
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-musl
checking host system type... x86_64-pc-linux-musl
checking target system type... x86_64-pc-linux-musl
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-zts-20180731
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
yes
checking for re2c... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking for pinpoint_php support... yes, shared
checking whether to enable pinpoint_php support... yes, shared
checking support test... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
------Build common libraries------------
-- Configuring done
-- Generating done
-- Build files have been written to: /root/pinpoint-c-agent/build
[ 40%] Built target jsoncpp
[ 50%] Building CXX object src/CMakeFiles/pinpoint_common.dir/Chunk.cpp.o
In file included from /root/pinpoint-c-agent/common/src/Chunk.cpp:22:0:
/root/pinpoint-c-agent/common/src/Chunk.h:37:9: error: 'uint' does not name a type
         uint block_size;
         ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:38:9: error: 'uint' does not name a type
         uint l_ofs; // The continuous buffer left offset in data ***(l_ofs)--------------(r_ofs)*****
         ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:39:9: error: 'uint' does not name a type
         uint r_ofs; // The continuous buffer right offset in data
         ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:52:11: error: 'uint' does not name a type
     const uint c_resident_size;
           ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:53:11: error: 'uint' does not name a type
     const uint c_max_size;    // if  ck_alloc_size > c_max_size buffer is full
           ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:54:5: error: 'uint' does not name a type
     uint threshold;
     ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:56:5: error: 'uint' does not name a type
     uint ck_alloc_size;
     ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:57:5: error: 'uint' does not name a type
     uint ck_free_list_size;
     ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:61:5: error: 'uint' does not name a type
     uint ck_ceil_to_k(uint i);
     ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:68:49: error: 'uint' has not been declared
     int copyDataIntoReadyList(const void* data, uint length);
                                                 ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:70:47: error: 'uint' has not been declared
     int copyDataIntoFreeList(const void*data, uint length);
                                               ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:72:48: error: 'uint' has not been declared
     int copyDataIntoNewChunk(const void* data, uint length);
                                                ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:78:24: error: 'uint' has not been declared
     bool useExistChunk(uint length);
                        ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:82:5: error: 'uint' does not name a type
     uint getAllocSize() const;
     ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:84:17: error: expected ')' before 'max_size'
     Chunks(uint max_size, uint resident_size);
                 ^~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.h:91:45: error: 'uint' has not been declared
     int copyDataIntoChunks(const void*data, uint length);
                                             ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:93:57: error: 'uint' was not declared in this scope
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                         ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:93:61: error: expression list treated as compound expression in functional cast [-fpermissive]
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                             ^
/root/pinpoint-c-agent/common/src/Chunk.h:93:62: error: template argument 1 is invalid
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                              ^
/root/pinpoint-c-agent/common/src/Chunk.h:93:57: error: 'uint' was not declared in this scope
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                         ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:93:61: error: expression list treated as compound expression in functional cast [-fpermissive]
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                             ^
/root/pinpoint-c-agent/common/src/Chunk.h:93:62: error: template argument 1 is invalid
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                              ^
/root/pinpoint-c-agent/common/src/Chunk.h:93:57: error: 'uint' was not declared in this scope
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                         ^~~~
/root/pinpoint-c-agent/common/src/Chunk.h:93:61: error: expression list treated as compound expression in functional cast [-fpermissive]
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                             ^
/root/pinpoint-c-agent/common/src/Chunk.h:93:62: error: template argument 1 is invalid
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                                              ^
/root/pinpoint-c-agent/common/src/Chunk.h:93:31: error: 'std::function' is not a type
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                               ^~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.h:93:39: error: expected ',' or '...' before '<' token
     int drainOutWithPipe(std::function<int(const char*, uint)> in_pipe_cb);
                                       ^
/root/pinpoint-c-agent/common/src/Chunk.cpp:24:53: error: 'uint' has not been declared
 int Chunks::copyDataIntoReadyList(const void* data, uint length)
                                                     ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: In member function 'int Chunks::copyDataIntoReadyList(const void*, int)':
/root/pinpoint-c-agent/common/src/Chunk.cpp:32:37: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'r_ofs'
     char* e_buf_start = &e->data[e->r_ofs];
                                     ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:33:5: error: 'uint' was not declared in this scope
     uint in_max_len = e->block_size - e->r_ofs;
     ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:36:13: error: 'in_max_len' was not declared in this scope
         if (in_max_len >= length)
             ^~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:39:16: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'r_ofs'
             e->r_ofs += length;
                ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:46:16: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'r_ofs'
             e->r_ofs += in_max_len;
                ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: At global scope:
/root/pinpoint-c-agent/common/src/Chunk.cpp:52:51: error: 'uint' has not been declared
 int Chunks::copyDataIntoFreeList(const void*data, uint length)
                                                   ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: In member function 'int Chunks::copyDataIntoFreeList(const void*, int)':
/root/pinpoint-c-agent/common/src/Chunk.cpp:66:47: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'r_ofs'
         char* f_buf_start = &free->data[free->r_ofs];
                                               ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:67:9: error: 'uint' was not declared in this scope
         uint in_max_len = free->block_size - free->r_ofs;
         ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:68:13: error: 'in_max_len' was not declared in this scope
         if (in_max_len >= length)
             ^~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:71:19: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'r_ofs'
             free->r_ofs += length;
                   ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:79:19: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'r_ofs'
             free->r_ofs += in_max_len;
                   ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:81:15: error: 'class Chunks' has no member named 'ck_free_list_size'; did you mean 'free_list'?
         this->ck_free_list_size -=free->block_size;
               ^~~~~~~~~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:81:41: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'block_size'
         this->ck_free_list_size -=free->block_size;
                                         ^~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: At global scope:
/root/pinpoint-c-agent/common/src/Chunk.cpp:92:1: error: 'uint' does not name a type
 uint Chunks::ck_ceil_to_k(uint i)
 ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:107:52: error: 'uint' has not been declared
 int Chunks::copyDataIntoNewChunk(const void* data, uint length)
                                                    ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: In member function 'int Chunks::copyDataIntoNewChunk(const void*, int)':
/root/pinpoint-c-agent/common/src/Chunk.cpp:109:57: error: 'ck_ceil_to_k' was not declared in this scope
     int block_size = ck_ceil_to_k(sizeof(Chunk) + length);
                                                         ^
/root/pinpoint-c-agent/common/src/Chunk.cpp:117:9: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'block_size'
     nc->block_size = block_size - sizeof(Chunk);
         ^~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:119:9: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'r_ofs'
     nc->r_ofs = length;
         ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:120:9: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'l_ofs'
     nc->l_ofs = 0;
         ^~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:123:11: error: 'class Chunks' has no member named 'ck_alloc_size'
     this->ck_alloc_size +=  block_size;
           ^~~~~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: In member function 'void Chunks::reduceFreeList()':
/root/pinpoint-c-agent/common/src/Chunk.cpp:133:15: error: 'class Chunks' has no member named 'ck_alloc_size'
         this->ck_alloc_size -= c->block_size + sizeof(Chunk);
               ^~~~~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:133:35: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'block_size'
         this->ck_alloc_size -= c->block_size + sizeof(Chunk);
                                   ^~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:134:15: error: 'class Chunks' has no member named 'ck_free_list_size'; did you mean 'free_list'?
         this->ck_free_list_size -= c->block_size;
               ^~~~~~~~~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:134:39: error: 'Chunks::Chunk {aka struct Chunks::chunk_}' has no member named 'block_size'
         this->ck_free_list_size -= c->block_size;
                                       ^~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: In member function 'void Chunks::checkWaterLevel()':
/root/pinpoint-c-agent/common/src/Chunk.cpp:141:18: error: 'class Chunks' has no member named 'c_resident_size'
     while (this->c_resident_size < this->ck_alloc_size
                  ^~~~~~~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:141:42: error: 'class Chunks' has no member named 'ck_alloc_size'
     while (this->c_resident_size < this->ck_alloc_size
                                          ^~~~~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: At global scope:
/root/pinpoint-c-agent/common/src/Chunk.cpp:149:1: error: 'uint' does not name a type
 uint Chunks::getAllocSize() const
 ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:154:15: error: expected constructor, destructor, or type conversion before '(' token
 Chunks::Chunks(uint max_size, uint resident_size) :
               ^
/root/pinpoint-c-agent/common/src/Chunk.cpp: In destructor 'virtual Chunks::~Chunks()':
/root/pinpoint-c-agent/common/src/Chunk.cpp:177:11: error: 'class Chunks' has no member named 'ck_free_list_size'; did you mean 'free_list'?
     this->ck_free_list_size = 0;
           ^~~~~~~~~~~~~~~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp: At global scope:
/root/pinpoint-c-agent/common/src/Chunk.cpp:180:28: error: 'bool Chunks::useExistChunk' is not a static data member of 'class Chunks'
 bool Chunks::useExistChunk(uint length)
                            ^~~~
/root/pinpoint-c-agent/common/src/Chunk.cpp:180:28: error: 'uint' was not declared in this scope
make[2]: *** [src/CMakeFiles/pinpoint_common.dir/build.make:63: src/CMakeFiles/pinpoint_common.dir/Chunk.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: src/CMakeFiles/pinpoint_common.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
----------------------------------------
checking for ld used by cc... /usr/x86_64-alpine-linux-musl/bin/ld
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking how to run the C++ preprocessor... g++ -E
checking the maximum length of command line arguments... 98304
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
`

**Comment by eeliu** [comment]
@lovexiongmao 

Which OS you used ？

**Comment by lovexiongmao** [comment]
alpline Linux  x86_64

**Comment by eeliu** [comment]
@lovexiongmao  

I created a branch for `uint`, https://github.com/eeliu/pinpoint-c-agent/tree/fix_uint.

As  `alpline Linux x86_64` environment not in the checking list, please help us.

When your compiled is done, shared the result to us.

Thanks

**Comment by lovexiongmao** [comment]
@eeliu 
I clone the branch and exec  ` ./configure --with-php-config=/usr/local/php/bin/php-config`
still get the same error like above.

**Comment by eeliu** [comment]
Join https://gitter.im/naver/pinpoint-c-agent?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by lovexiongmao** [comment]
eeliu had fix it
