### ISSUE TITLE
error: possibly undefined macro: AM_EXTRA_RECURSIVE_TARGETS

### ISSUE THREAD

**Issue by tangleiao** [naver/pinpoint-c-agent#23]
HI guy：
       when i run ./Build.sh, I got some errors , can you help me?  
      os  is centos 6.8
      autoconf version :   2.68
      automake version : 1.6.3

      Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
configure.ac:110: warning: macro `AM_EXTRA_RECURSIVE_TARGETS' not found in library
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
aclocal/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
aclocal/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal/libtool.m4:5343: _LT_LANG_CXX_CONFIG is expanded from...
aclocal/libtool.m4:785: _LT_LANG is expanded from...
aclocal/libtool.m4:768: LT_LANG is expanded from...
aclocal/libtool.m4:796: _LT_LANG_DEFAULT_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
aclocal/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
aclocal/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal/libtool.m4:5343: _LT_LANG_CXX_CONFIG is expanded from...
aclocal/libtool.m4:785: _LT_LANG is expanded from...
aclocal/libtool.m4:768: LT_LANG is expanded from...
aclocal/libtool.m4:796: _LT_LANG_DEFAULT_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
aclocal/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
aclocal/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:93: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:194: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2662: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2679: AC_LINK_IFELSE is expanded from...
aclocal/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal/libtool.m4:5343: _LT_LANG_CXX_CONFIG is expanded from...
aclocal/libtool.m4:785: _LT_LANG is expanded from...
aclocal/libtool.m4:768: LT_LANG is expanded from...
aclocal/libtool.m4:796: _LT_LANG_DEFAULT_CONFIG is expanded from...
aclocal/libtool.m4:138: _LT_SETUP is expanded from...
aclocal/libtool.m4:67: LT_INIT is expanded from...
aclocal/libtool.m4:102: AC_PROG_LIBTOOL is expanded from...
configure.ac:93: the top level
configure.ac:110: error: possibly undefined macro: AM_EXTRA_RECURSIVE_TARGETS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by tangleiao** [comment]
I have upgraded to 2.69, but it is still the mistake.

**Comment by ChenGXQQ** [comment]
Please refer this:
https://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error
