### ISSUE TITLE
only support php-fpm application?

### ISSUE THREAD

**Issue by Louis-Sen** [naver/pinpoint-c-agent#30]
have plan to support php-cli php application?

**Comment by ChenGXQQ** [comment]
Can you tell us which php-cli application you want to support? We are designing new features of our agent. If it is feasible, we'll consider to support it.

**Comment by Louis-Sen** [comment]
My project use Workerman framework (https://github.com/walkor/workerman), Basic Usage: An http server.
When php-cli project started, PHP_MSHUTDOWN_FUNCTION function will execute so  php agent stop. All xxxTask quit

**Comment by xiaooloong** [comment]
Is there any plan to support [`swoft`](https://github.com/swoft-cloud/swoft) or [`swoole`](https://github.com/swoole/swoole-src) ?
:D

**Comment by ChenGXQQ** [comment]
Hi all,
We are invertigating to support cli and which is supported firstly depends on their popularity. Please be patient. ^_^

**Comment by RoySRose** [comment]
Hello, @billowqiu 

There are few who are trying to create GO agent and asked few questions but never heard from them after since.

**Comment by kirachen1991** [comment]
I'm waiting for this feature……I wish it will come soon……= =！！！

**Comment by eeliu** [comment]
[v0.2.1](https://github.com/naver/pinpoint-c-agent/releases/tag/v0.2.1) had supported  r swoole/workmen, please check that.
