### ISSUE TITLE
show cross application calls icon ?

### ISSUE THREAD

**Issue by kdszh** [naver/pinpoint-c-agent#34]
Hi, how can I make my mysql plugin show icon as below with pinpoint-c-agent?  some options or code sample?

![mysql](https://user-images.githubusercontent.com/2100801/46254796-8c871880-c4c7-11e8-831b-911a3162c727.png)

**Comment by ChenGXQQ** [comment]
Until now, you can't. The core problem is that we don't want to mix Java plugin and PHP plugin together. We are trying to find a solution. If you really want to, you can read Java mysql plugin and implant to PHP.

**Comment by kdszh** [comment]
Ok, thanks.
