### ISSUE TITLE
Build Agent Error

### ISSUE THREAD

**Issue by xujunhai** [naver/pinpoint-c-agent#35]
hi~
when i run Build.sh，got the error：
fatal error: thrift/cxxfunctional.h: No such file or directory

Linux: CentOS Linux release 7.3.1611 (Core)
Thanks

**Comment by xujunhai** [comment]
hi~ friends:
i resolve the problem， because there's a  bug in code.

in pinpoint_common/thrift/gen-cpp/Command_types.h
`#include<thrift/cxxfunctional.h>` 
does't exist the header file in library dependency really.
it should be  
`#include<thrift/stdxx.h>` ?
Hope to fix it 
Thanks

**Comment by ChenGXQQ** [comment]
@xujunhai 
The files in pinpoint_common/thrift/gen-cpp/ are generated by thrift. It is not recommended to modify them if you have very feasible reason.

**Comment by xujunhai** [comment]
@eeliu 
yes . use Thrift 0.11.0

**Comment by xujunhai** [comment]
@ChenGXQQ 
But when i follow the installation tutorial, execute the Build.sh,  an error occurred. There does't exists cxxfunction.h in my /usr/local/include/thrift(installed thrift libarary)

how should i do?

Thnanks

**Comment by eeliu** [comment]
hi @xujunhai 
I found out the reason, pls checkout out the dev branch.

**Comment by eeliu** [comment]
@xujunhai  
yes, it does. 
And the good news, this week we will release v0.1.1.
Thanks

**Comment by xujunhai** [comment]
@eeliu
very much look forward to it
Thanks

**Comment by eeliu** [comment]
https://github.com/naver/pinpoint-c-agent/releases/tag/v0.2.0 had removed such dependencies in module level, I recommend you to use this version instead.
So I close this version.
