### ISSUE TITLE
Ubutu release package is needed

### ISSUE THREAD

**Issue by baoshengzhu** [naver/pinpoint-c-agent#37]
os version:      Ubuntu 12.04 LTS  and  Ubuntu 16.04 LTS
php version:   PHP 5.4.42 
nginx/1.12.2

**Comment by eeliu** [comment]
@baoshengzhu 

If you meet problem when compiling agent, don't hesitage to tell us.

Goto [README.md](https://github.com/naver/pinpoint-c-agent/blob/dev/README.md)

**Comment by eeliu** [comment]
Too long to trace, just close it.
