### ISSUE TITLE
PHP 7.1.11 Curl Plugin issue 

### ISSUE THREAD

**Issue by riteshsoni10** [naver/pinpoint-c-agent#38]
**Environment**
PHP 7.1.11
Centos 7.4
php-c-agent 1.60 from git clone https://github.com/naver/pinpoint-c-agent.git
boost 1.63
thrift 0.11

Followed steps from **https://github.com/naver/pinpoint-c-agent/tree/dev**

I am unable to resolve this issue . Whenever I embed pinpoint-c-agent in my php.ini. I start to get SEGMENTATION FAULT errors in my apache logs.

And the pinpoint log contains the following lines:

16:02:15 [pinpoint] [30336] php_common.cpp:961 [ERROR] w_zend_call_method throw: [exception: Undefined index: Resource id #501 in /opt/pinpoint-c-agent/quickstart/php/web/plugins/curl_plugin.php on line 37]
16:02:15 [pinpoint] [30336] php_interfaces.cpp:969 [ERROR] Interceptor name=[curl_exec] onbefore failed!!! please check your code!!!
16:02:15 [pinpoint] [30336] trace.cpp:481 [ERROR] mark bad trace !!! check your plugins...

It would be nice if anyone could help me out. I am a newbie in pinpoint

**Comment by riteshsoni10** [comment]
No. I am not using PHP multi thread

**Comment by riteshsoni10** [comment]
@ChenGXQQ

**Comment by riteshsoni10** [comment]
@ChenGXQQ  We are not using PHP multi Thread. 

It would be nice if you can help with this. I am struggling with this past few days.

**Comment by ChenGXQQ** [comment]
@riteshsoni10 Can you give us more information? How does your PHP configure? The compile option? The php.ini file? and the core file of SEGMENTATION FAULT? And what mode of you apache? (We don't support workers)

**Comment by ChenGXQQ** [comment]
@riteshsoni10 
Can you tell me which version you checkout? the commit id.

**Comment by eeliu** [comment]
@riteshsoni10 
which cgi you used, libphp5.so or php-fpm ?

We can't reproduce it, pls give us more information, if it convenient.

1. full pinpint_agent.log
2. httpd.conf
3. gcc verion

**Comment by ChenGXQQ** [comment]
@riteshsoni10 
Can you give us the PHP file you visited? Or tell us how you call curl functions.

**Comment by riteshsoni10** [comment]
@ChenGXQQ 
I am more concerned with the SEGMENTATION faults that starts arriving in my apache error logs as soon as i embedd php-c-agent in my php .

And being the production environment I cant help it out and have to immediately remove the plugin as it causes error at the client side

**Comment by riteshsoni10** [comment]
@ChenGXQQ @eeliu Callstack is variable for different APIs. We're using laravel and having around 150 APIs. So these APIs lands to different controllers and access through Models and libraries.

**Comment by eeliu** [comment]
@riteshsoni10 

Hi, if you use laravel . I strongly recommand you update the pinpint-agent to [v0.2.0](https://github.com/naver/pinpoint-c-agent/releases/tag/v0.2.0) . It fully supports ZTS and curl, hope you to use it.
