### ISSUE TITLE
Generate the topology diagram

### ISSUE THREAD

**Issue by baoshengzhu** [naver/pinpoint-c-agent#48]
The agent failed to produce topology information for linked data and invocation information for the database

**Comment by ChenGXQQ** [comment]
Emm... Can you give us more information? I can not get a clue from comment above.

**Comment by ChenGXQQ** [comment]
Please refer to https://github.com/naver/pinpoint-c-agent/issues/34

**Comment by baoshengzhu** [comment]
Ok, thanks.
