### ISSUE TITLE
The PHP agent causes the CPU load to be too high

### ISSUE THREAD

**Issue by baoshengzhu** [naver/pinpoint-c-agent#49]
When the collector is lost, the CPU load on the agent's host is too high

**Comment by ChenGXQQ** [comment]
If the connectio is lost, the agent will try to reconnection. It exhausts the CPU and the peak is 30% in my machine. Can you tell me how many in your server? I think 30% is acceptable.

**Comment by baoshengzhu** [comment]
CPU usage is acceptable, but CPU loads are hundreds and rising.

**Comment by eeliu** [comment]
@baoshengzhu 

Could you mind give the pinpoint_log.txt (when CPU load rising too high) to us. We need more information about it.

**Comment by baoshengzhu** [comment]
[log.txt.tar.gz](https://github.com/naver/pinpoint-c-agent/files/2532564/log.txt.tar.gz)
It happened on 2018-10-25 15:20:00 -- 2018-10-25 15:30:00

**Comment by eeliu** [comment]
@baoshengzhu 

pinpoint-c-agent had released v0.2.0,hope you to  upgrade it. This version separated the agent logic,made it more safe and efficiency.
So I close this issue, if you find problems on v0.2.0, please reopen it or create a new one.
