### ISSUE TITLE
Want to Linking libstdc++ and libgcc statically

### ISSUE THREAD

**Issue by ZuLiHu** [naver/pinpoint-c-agent#52]
Hi ,
When I run PHP, I get the following error：

_[05-Nov-2018 14:21:19 PRC] PHP Warning:  PHP Startup: Unable to load dynamic library '/home/homework/php/ext/pinpoint.so' - /mnt/homework/php/bin/../../lib/gcc-3.4.5/libstdc++.so.6: version `CXXABI_1.3.1' not found (required by /home/homework/php/ext/pinpoint.so) in Unknown on line 0_

I run ldd and got the following results:
ldd pinpoint.so
	libboost_system.so.1.63.0 => /usr/local/lib/libboost_system.so.1.63.0 (0x00007f9456a65000)
	libboost_thread.so.1.63.0 => /usr/local/lib/libboost_thread.so.1.63.0 (0x00007f9456841000)
	libboost_filesystem.so.1.63.0 => /usr/local/lib/libboost_filesystem.so.1.63.0 (0x00007f945662a000)
	libboost_date_time.so.1.63.0 => /usr/local/lib/libboost_date_time.so.1.63.0 (0x00007f9456416000)
	libthrift-0.11.0.so => /usr/local/lib/libthrift-0.11.0.so (0x00007f94560ad000)
	
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f9456c69000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f945587e000)

（I Can't Upgrade libstdc++. So.6 and libc.so.6 for my PHP）
I want to linking libstdc++ 、 libgcc 、libboost、libthrift statically，make their so not in ldd result.

Please tell me how to config。

**Comment by eeliu** [comment]
@ZuLiHu 
Did you copy the pinpoint.so from other environment?

**Comment by ZuLiHu** [comment]
> @ZuLiHu
> Did you copy the pinpoint.so from other environment?

My PHP reference it's own library not the system libraries。So, pinpoint.so become a php extension，pinpoint.so not reference the system libraries，its reference PHP's libstdc++.so.6 and libc.so.6 not System's libstdc++.so.6 and libc.so.6。
But I build pinpoint.so use System gcc，so,when run pinpoint.so error。

**Comment by ZuLiHu** [comment]
@eeliu Can you help me?

**Comment by eeliu** [comment]
@ZuLiHu 

If you want to link static library, use "./Build.sh --enable-release". 
BUT, keep in mind that all libraries must support -fPIC when compiled, and only boost and thrift is supported. [This is an experiment function]


https://github.com/naver/pinpoint-c-agent/blob/a8f7c16cc783d505aa386ac77046ce193dd23747/pinpoint_php/config.m4#L26-L30


For you php , use system libraries is a solution, as pinpint.so needs them.

**Comment by eeliu** [comment]
@ZuLiHu 

hi, does your PHP application support composer classloader ?

**Comment by eeliu** [comment]
Hi, this is a deployment problem
https://github.com/naver/pinpoint-c-agent/releases/tag/v0.2.0 provided a better solution on such scene. Hope you clone it and upgrade it. Thanks
