### ISSUE TITLE
undefined symbol: _call_user_function_ex in Unknown on line 0

### ISSUE THREAD

**Issue by weijieliefu** [naver/pinpoint-c-agent#53]
when i startup the php it always report errors of NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/pinpoint.so' - /usr/local/lib/pinpoint.so: undefined symbol: _call_user_function_ex in Unknown on line 0
Could you help me solve this problem?

**Comment by ChenGXQQ** [comment]
@weijieliefu How do you compile the agent?

**Comment by weijieliefu** [comment]
phpize--Build.sh--make install.Then get pinpoint.so

**Comment by weijieliefu** [comment]
[root@localhost pinpoint_php]# phpize -v
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012

Is this same version ?

**Comment by ChenGXQQ** [comment]
What is your PHP version?

**Comment by weijieliefu** [comment]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20170718/pinpoint.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20170718/pinpoint.so: undefined symbol: _call_user_function_ex in Unknown on line 0
PHP 7.0.32 (cli) (built: Sep 15 2018 09:14:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.32, Copyright (c) 1999-2017, by Zend Technologies

**Comment by ChenGXQQ** [comment]
Your PHP version and phpize version are different.
please refer this:
https://zend18.zendesk.com/hc/en-us/articles/217058968-PHP-Versions-and-APIs

**Comment by ChenGXQQ** [comment]
Please use the compatible version!

**Comment by weijieliefu** [comment]
OK thank you。
