### ISSUE TITLE
all methods name in call stack tree are "date:10"

### ISSUE THREAD

**Issue by haroldjiang** [naver/pinpoint-c-agent#56]
all methods name in call stack tree are "date:10",can't help to locate the problem

**Comment by haroldjiang** [comment]
<img width="1394" alt="pinpoint-c-agent" src="https://user-images.githubusercontent.com/6148110/48187529-54041580-e376-11e8-8d04-e243619c3c30.png">

**Comment by haroldjiang** [comment]
<img width="1202" alt="pinpoint-web-log" src="https://user-images.githubusercontent.com/6148110/48190870-b5c87d80-e37e-11e8-8838-e6ded93c4b6b.png">
<img width="1430" alt="pinpoint-log-agent" src="https://user-images.githubusercontent.com/6148110/48190871-b6611400-e37e-11e8-83ef-f43d1f7e4fc6.png">

**Comment by ChenGXQQ** [comment]
I guess your server crashed. Can you see if there are some .core files in you server?

**Comment by eeliu** [comment]
Hi, version 0.2.0 released,made debug  such scene be more easy.
We remmanded you upgrade.
So I close this issue
