### ISSUE TITLE
when i restart php-fpm  pinpoint_logs.txt is not achived 

### ISSUE THREAD

**Issue by json-lihao** [naver/pinpoint-c-agent#60]
excute this commond  : php -m |grep pinpoint
return "pinpoint"
my pinpoint_agent.conf  below
AgentID=calculation
ApplicationName=calculationApplication

## collector ip address
CollectorSpanIp=10.28.3.136
CollectorSpanPort=9996
CollectorStatIp=10.28.3.136
CollectorStatPort=9995
CollectorTcpIp=10.28.3.136
CollectorTcpPort=9994

TraceLimit = -1
SkipTraceTime = -1
# DEBUG|INFO|WARN|ERROR
PPLogLevel = INFO
LogFileRootPath =/data/logs
# AgentType -> NGINX | APACHE |PHP |TEST
AgentType=PHP

# plugin
# PhpInternalFunctionsPlugin
PluginExclude = ExcludePlugin
PluginInclude = PhpRequestPlugin;QuickStartPlugin  ; PhpInternalFunctionsPlugin ;ExcludePlugin ;PDOPlugin;CurlPlugin;

[PHP]
PluginEntryFile=plugins_create.php
PluginRootDir=/usr/share/nginx/html/pinpoint_plugins
;eg: PluginRootDir=/home/apps/php-7.1.0/pinpoint/web/php/plugins

hope you can help me

**Comment by eeliu** [comment]
Did you mean that the  pinpoint_logs.txt is missing ?
From your pinpint_agent.conf, your logging path is "/data/logs".
If it not found, maybe your PHP configuration not appropriately.

**Comment by ChenGXQQ** [comment]
And please ensure that you have write permission to this folder.

**Comment by json-lihao** [comment]
> Did you mean that the pinpoint_logs.txt is missing ?
> From your pinpint_agent.conf, your logging path is "/data/logs".
> If it not found, maybe your PHP configuration not appropriately.

i have set the write permission to this folder 
root@qacalculation-mxj-mx-577758569b-9zwzx:/data# ll
drwxrwxrwx  2 root root   4096 Dec 12 09:43 logs/ 
and how could i make sure my php configuration is correct?
i follow the steps 
 and make install pinpoint.so successfully 
my php.ini config is below
[pinpoint]
extension=/usr/lib/php/20160303/pinpoint.so
pinpoint_agent.config_full_name=/etc/pinpoint_agent.conf

**Comment by ChenGXQQ** [comment]
Firstly, if your pinpoint agent has error, you can found error message at php.log. Then, when agent starts correctly, all log will be written at pinpoint_logs.txt.

**Comment by eeliu** [comment]
@json-lihao  Please give us more information, include php.log and php-fpm.log.

**Comment by eeliu** [comment]
The latest release, v0.2.0 make trace and debug more easy. It's worth to have a try.
So I closed this issue.
