### ISSUE TITLE
can we configure appliationname option based on web application

### ISSUE THREAD

**Issue by claytonxia** [naver/pinpoint-c-agent#61]
Hi,

is configuration option "ApplicationName" available for application so that we can seperate traces according to different application instance. For example, i define the option in the entrance file of php framework.

Thanks.

**Comment by eeliu** [comment]
Untill now, php.ini is the only place to set "ApplicationName". 
Do you want to set the "ApplicationName" in your application?

**Comment by claytonxia** [comment]
@eeliu 
yes, since it is common to run several applications on same server while we want to see call details seperatly.
