### ISSUE TITLE
detailed plugin api

### ISSUE THREAD

**Issue by claytonxia** [naver/pinpoint-c-agent#62]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> Please describe the behavior you are expecting

# Current Behavior

> What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:

* PHP Version:

* php.ini:

* php-fpm or apache:

* pinpoint_agent.conf:

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )

**Comment by claytonxia** [comment]
sorry for the mistaken issue.

**Comment by eeliu** [comment]
That's all right.
