### ISSUE TITLE
how is failed/successful response defined

### ISSUE THREAD

**Issue by claytonxia** [naver/pinpoint-c-agent#63]
Hi,

I wanna know how the successful reponse and failed response are defined. I tried locally and found that the response was regarded as successful one even the status code is 4xx or 5xx.

thanks.

**Comment by eeliu** [comment]
Agent DOES NOT define the request, just checking the error(or uncatched exception).

**Comment by claytonxia** [comment]
@eeliu  
can agent check according to response status code

**Comment by eeliu** [comment]
Current release not support this.

**Comment by eeliu** [comment]
Later we will some api to support it.
