### ISSUE TITLE
About the inability to add interceptors for mysqlnd-based PHP extensions in "PHP5.6"; Example: Pdo & Mysqli & Mysql

### ISSUE THREAD

**Issue by yuslf** [naver/pinpoint-c-agent#64]
* Operating System: Centos 6.10

* PHP Version: php 5.6

Pdo, Mysqli, Mysql

**Comment by yuslf** [comment]
[https://github.com/yuslf/pinpoint-c-agent/blob/dev/quickstart/php/web/plugins/mysqli_plugin.php](mysqli_plugin.php)
[https://github.com/yuslf/pinpoint-c-agent/blob/dev/quickstart/php/web/plugins/mysqli_func_plugin.php](mysqli_func_plugin.php)
[https://github.com/yuslf/pinpoint-c-agent/blob/dev/quickstart/php/web/plugins/pdo_plugin.php](pdo_plugin.php)
[https://github.com/yuslf/pinpoint-c-agent/blob/dev/quickstart/php/web/plugins/plugins_create.php](plugins_create.php)
[https://github.com/yuslf/pinpoint-c-agent/blob/dev/quickstart/php/web/interceptor.php](interceptor.php)
[https://github.com/yuslf/pinpoint-c-agent/blob/dev/quickstart/config/pinpoint_agent.conf.example](pinpoint_agent.conf.example)

In PHP 5.6, the onBefore methods of these interceptors will not execute and there is no error message.But in PHP 7.2 they can work properly.

**Comment by yuslf** [comment]
I also wrote some other interceptors.For example: Curl, Redis, Memcache, these interceptors can work either in PHP 5.6 or in PHP 7.2.

**Comment by ChenGXQQ** [comment]
@yuslf Thanks for reporting. We'll investigate ASAP.

**Comment by EyelynSu** [comment]
@yuslf 
I tried in my env, agent runs normally, function in mysqli and pdo can be monitored.
![1546420931](https://user-images.githubusercontent.com/41946743/50586433-5e451a80-0eb4-11e9-846d-caaec4d27c0d.png)

**[env]**
php-5.6.39
pinpoint-c-agent: v0.1.1rc1

**Comment by ChenGXQQ** [comment]
@yuslf Please clarify us the exact PHP version, include the minimum version number.

**Comment by yuslf** [comment]
um, like this.

---------------------------------------------------------------------

PHP 5.6.17 (cli) (built: Feb 11 2016 00:41:07)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

---------------------------------------------------------------------

CentOS release 6.9 (Final)

Linux version 2.6.32-696.20.1.el6.x86_64 (mockbuild@x86_64_01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Fri Jan 26 17:51:45 UTC 2018

---------------------------------------------------------------------

and, i used my modified pinpoint, maybe this will become a problem, but, it is OK on PHP 7.2.

https://github.com/yuslf/pinpoint-c-agent

**Comment by EyelynSu** [comment]
@yuslf @ChenGXQQ 
I tried on env with php 5.6.17 and centos6.9, Interceptors works normally:
![1546587565-centos69](https://user-images.githubusercontent.com/41946743/50678061-e30c7180-1037-11e9-9786-590cae3a5536.png)

**[env]**
php-5.6.17
pinpoint-c-agent: v0.1.1rc1
centos6.9

**Comment by yuslf** [comment]
OK... it should be my env problem. Thinks.
