### ISSUE TITLE
when i restart php-fpm,pinpoint can't collect data.

### ISSUE THREAD

**Issue by atsuko0710** [naver/pinpoint-c-agent#65]
#### PHP 5.6.36、CentOS Linux release 7.6.1810 (Core)、nginx/1.14.1、Boost  1.5.8+、 Thirft  0.11.0+、 gcc  4.4.7+
---
### php.ini
[pinpoint]
extension= /usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/pinpoint.so
pinpoint_agent.trace_exception=true
pinpoint_agent.config_full_name=/usr/local/php/etc/pinpoint_agent.conf
### pinpoint_agent.conf
[pinpoint_agent.conf.txt](https://github.com/naver/pinpoint-c-agent/files/2714647/pinpoint_agent.conf.txt)
### pinpoint_log.txt
[pinpoint_log.txt](https://github.com/naver/pinpoint-c-agent/files/2714650/pinpoint_log.txt)
### plugin files
[curl_plugin.php.txt](https://github.com/naver/pinpoint-c-agent/files/2714660/curl_plugin.php.txt)
[plugins_create.php.txt](https://github.com/naver/pinpoint-c-agent/files/2714661/plugins_create.php.txt)
[quickstart_plugin.php.txt](https://github.com/naver/pinpoint-c-agent/files/2714662/quickstart_plugin.php.txt)
[exclude_plugin.php.txt](https://github.com/naver/pinpoint-c-agent/files/2714665/exclude_plugin.php.txt)

---
i try to delete  pinpoint_log.txt and visit any page,it can't  automatic generation,and when i execute 'php -m','pinpoint_log.txt' will be generated.

**Comment by ChenGXQQ** [comment]
Hi, I saw your pinpoint_log.txt. It seems that the agent can't connect to the collector. Please ensure the 9994 port is ok. Search "ERROR" in this file. You can see this error message.

**Comment by eeliu** [comment]
From the context, the problem had done.
