### ISSUE TITLE
php 7.1.9 fpm 502

### ISSUE THREAD

**Issue by claytonxia** [naver/pinpoint-c-agent#67]
Hi, 

i deployed pinpoint with php version of 7.1.9, but the the fpm always restart after each request. i didn't modify the quickstart plugin and i am not using multithreading extension. i looked up  the php-fpm.log and i found many error like `[15-Jan-2019 18:01:06] WARNING: [pool www] child 21796 exited on signal 11 (SIGSEGV) after 5.900995 seconds from start`.

could anyone help me out? 

thanks.

**Comment by EyelynSu** [comment]
Hi,
can you tell us:
1, the core file;[How to config and debug core file](https://github.com/naver/pinpoint-c-agent/wiki/Core-dump-file-configuration-and-debugging.)
2, which branch do you checkout, and your pinpoint-agent.conf file;

**Comment by claytonxia** [comment]
Hi,
i checked out both the dev and master branch and reported 502; the pinpoint-agent.conf file is the same as quickstart.
i will try debug core file.
thanks.

**Comment by ChenGXQQ** [comment]
@claytonxia Do you use mulithread in PHP? It is not supported now and I think it is really a emergence to support it (maybe next version).

**Comment by claytonxia** [comment]
@ChenGXQQ 
Hi,
we are not using multithread.
thanks.

**Comment by claytonxia** [comment]
Hi,

is there something else i can do to help locate the problem.

**Comment by eeliu** [comment]
We are working on it, this is hard to reproduce !

**Comment by claytonxia** [comment]
Please feel free to ask me for extra information.
thanks for your work.

**Comment by wasgosu** [comment]
I have the same problem.
Is there a solution?..
The php-fpm process is dead and a 502 error occurs.

[root@5576024855ca /]# ps -ef|grep php-fpm
root      1507     1  0 09:37 ?        00:00:00 php-fpm: master process (/etc/php-fpm.conf)
webmast+  1509  1507  0 **09:37** ?        00:00:00 php-fpm: pool www
webmast+  1643  1507  0 **09:39** ?        00:00:00 php-fpm: pool www
webmast+  1643  1507  0 **09:40** ?        00:00:00 php-fpm: pool www
webmast+  1652  1507  0 **09:41** ?        00:00:00 php-fpm: pool www
webmast+  1653  1507  0 **09:42** ?        00:00:00 php-fpm: pool www


2019-03-28 10:52:00 [pinpoint] [3085] pinpoint_agent.cpp:44 [DEBUG] start=2019-Mar-28 10:52:00
 2019-03-28 10:52:00 [pinpoint] [3085] pinpoint_agent.cpp:49 [DEBUG] beyondOneSecond: start=2019-Mar-28 10:52:00
 2019-03-28 10:52:00 [pinpoint] [3085] pinpoint_agent.cpp:50 [DEBUG] beyondOneSecond: end=2019-Mar-28 10:52:00
 2019-03-28 10:52:00 [pinpoint] [3085] pinpoint_agent.cpp:52 [DEBUG] beyondOneSecond: second=0
 2019-03-28 10:52:00 [pinpoint] [3085] memory_pool.h:118 [DEBUG] SafeShareMemory ProcsSharefeData-1553770256242 size 208
 2019-03-28 10:52:00 [pinpoint] [3085] memory_pool.h:135 [DEBUG] SafeShareMemory:ProcsSharefeData-1553770256242 pid:3084

**Comment by wasgosu** [comment]
I confirmed it as a process-down dump.

- text.txt 로그 내용 (핀포인트 켰을때..)
{sa_family=AF_LOCAL, NULL}, [2]) = 5
poll([{fd=5, events=POLLIN}], 1, 5000)  = 1 ([{fd=5, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {274208, 532353271}) = 0
times({tms_utime=16, tms_stime=40, tms_cutime=0, tms_cstime=0}) = 4322358149
read(5, "\1\1\0\1\0\10\0\0", 8)         = 8
read(5, "\0\1\1\0\0\0\0\0", 8)          = 8
read(5, "\1\4\0\1\2\31\7\0", 8)         = 8
read(5, "\f\0QUERY_STRING\16\3REQUEST_METHODGE"..., 544) = 544
read(5, "\1\4\0\1\0\0\0\0", 8)          = 8
lstat("/cjo/docs/vertical/pub/index.php", {st_mode=S_IFREG|0755, st_size=1246, ...}) = 0
lstat("/cjo/docs/vertical/pub", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/cjo/docs/vertical", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/cjo/docs", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
lstat("/cjo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
clock_gettime(CLOCK_MONOTONIC, {274208, 554220571}) = 0
gettimeofday({1553833339, 29374}, NULL) = 0
gettimeofday({1553833339, 29488}, NULL) = 0
stat("/cjo/docs/vertical/pub/.user.ini", {st_mode=S_IFREG|0755, st_size=101, ...}) = 0
open("/cjo/docs/vertical/pub/.user.ini", O_RDONLY) = 23
ioctl(23, TCGETS, 0x7ffe61bc5400)       = -1 ENOTTY (Inappropriate ioctl for device)
fstat(23, {st_mode=S_IFREG|0755, st_size=101, ...}) = 0
mmap(NULL, 133, PROT_READ, MAP_PRIVATE, 23, 0) = 0x7f1c925c5000
lseek(23, 0, SEEK_CUR)                  = 0
munmap(0x7f1c925c5000, 133)             = 0
close(23)                               = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={0, 0}}, NULL) = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={18000, 0}}, NULL) = 0
rt_sigaction(SIGPROF, NULL, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, 8) = 0
rt_sigaction(SIGHUP, NULL, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, 8) = 0
rt_sigaction(SIGINT, NULL, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, 8) = 0
rt_sigaction(SIGQUIT, NULL, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, 8) = 0
rt_sigaction(SIGTERM, NULL, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, 8) = 0
rt_sigaction(SIGUSR1, NULL, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, 8) = 0
rt_sigaction(SIGUSR2, NULL, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, 8) = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={60, 0}}, NULL) = 0
rt_sigaction(SIGPROF, {0x5622f83f1a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f1c8f69c280}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [PROF], NULL, 8) = 0
write(3, "2019-03-29 04:22:19 [pinpoint] ["..., 97) = 97
write(3, "2019-03-29 04:22:19 [pinpoint] ["..., 114) = 114
write(3, "2019-03-29 04:22:19 [pinpoint] ["..., 112) = 112
write(3, "2019-03-29 04:22:19 [pinpoint] ["..., 96) = 96
open("/dev/shm/ProcsSharefeData-1553771085670", O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 EEXIST (File exists)
open("/dev/shm/ProcsSharefeData-1553771085670", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = 23
fstat(23, {st_mode=S_IFREG|0644, st_size=208, ...}) = 0
write(3, "2019-03-29 04:22:19 [pinpoint] ["..., 122) = 122
fstat(23, {st_mode=S_IFREG|0644, st_size=208, ...}) = 0
mmap(NULL, 208, PROT_READ|PROT_WRITE, MAP_SHARED, 23, 0) = 0x7f1c925c5000
write(3, "2019-03-29 04:22:19 [pinpoint] ["..., 123) = 123
gettimeofday({1553833339, 36904}, NULL) = 0
clock_gettime(CLOCK_MONOTONIC, {274208, 562003871}) = 0
getcwd("/", 4095)                       = 2
chdir("/cjo/docs/vertical/pub")         = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={18000, 0}}, NULL) = 0
fcntl(4, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1, l_len=1}) = 0
access("/cjo/docs/vertical/app/etc/vendor_path.php", F_OK) = 0
access("/cjo/docs/vertical/./vendor/autoload.php", F_OK) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1e} ---
+++ killed by SIGSEGV +++


### 핀포인트 껐을때..
accept(9, {sa_family=AF_LOCAL, NULL}, [2]) = 4
poll([{fd=4, events=POLLIN}], 1, 5000)  = 1 ([{fd=4, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {275275, 863126771}) = 0
times({tms_utime=0, tms_stime=0, tms_cutime=0, tms_cstime=0}) = 4322464882
read(4, "\1\1\0\1\0\10\0\0", 8)         = 8
read(4, "\0\1\1\0\0\0\0\0", 8)          = 8
read(4, "\1\4\0\1\5\246\2\0", 8)        = 8
read(4, "\f\0QUERY_STRING\16\3REQUEST_METHODGE"..., 1448) = 1448
read(4, "\1\4\0\1\0\0\0\0", 8)          = 8
lstat("/cjo/docs/vertical/pub/index.php", {st_mode=S_IFREG|0755, st_size=1246, ...}) = 0
lstat("/cjo/docs/vertical/pub", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/cjo/docs/vertical", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/cjo/docs", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
lstat("/cjo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
clock_gettime(CLOCK_MONOTONIC, {275275, 863570971}) = 0
brk(NULL)                               = 0x555e781d8000
brk(0x555e781fb000)                     = 0x555e781fb000
brk(NULL)                               = 0x555e781fb000
brk(0x555e7821c000)                     = 0x555e7821c000
gettimeofday({1553834405, 86525}, NULL) = 0
gettimeofday({1553834405, 86580}, NULL) = 0
stat("/cjo/docs/vertical/pub/.user.ini", {st_mode=S_IFREG|0755, st_size=101, ...}) = 0
open("/cjo/docs/vertical/pub/.user.ini", O_RDONLY) = 5
ioctl(5, TCGETS, 0x7ffecf4429d0)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(5, {st_mode=S_IFREG|0755, st_size=101, ...}) = 0
mmap(NULL, 133, PROT_READ, MAP_PRIVATE, 5, 0) = 0x7f2af48f0000
lseek(5, 0, SEEK_CUR)                   = 0
munmap(0x7f2af48f0000, 133)             = 0
close(5)                                = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={0, 0}}, NULL) = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={18000, 0}}, NULL) = 0
rt_sigaction(SIGPROF, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGPROF, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
rt_sigaction(SIGHUP, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGHUP, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
rt_sigaction(SIGINT, NULL, {SIG_DFL, [], SA_RESTORER, 0x7f2af19c6280}, 8) = 0
rt_sigaction(SIGINT, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {0x555e75f9e030, [], SA_RESTORER|SA_RESTART, 0x7f2af19c6280}, 8) = 0
rt_sigaction(SIGQUIT, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {SIG_DFL, [], SA_RESTORER, 0x7f2af19c6280}, 8) = 0
rt_sigaction(SIGTERM, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
rt_sigaction(SIGUSR1, NULL, {SIG_DFL, [], SA_RESTORER, 0x7f2af19c6280}, 8) = 0
rt_sigaction(SIGUSR1, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
rt_sigaction(SIGUSR2, NULL, {SIG_DFL, [], SA_RESTORER, 0x7f2af19c6280}, 8) = 0
rt_sigaction(SIGUSR2, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={60, 0}}, NULL) = 0
rt_sigaction(SIGPROF, {0x555e75f09a40, ~[ILL TRAP ABRT BUS FPE KILL SEGV CONT STOP TSTP TTIN TTOU SYS RTMIN RT_1], SA_RESTORER|SA_SIGINFO, 0x7f2af19c6280}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [PROF], NULL, 8) = 0
clock_gettime(CLOCK_MONOTONIC, {275275, 865220271}) = 0
getcwd("/", 4095)                       = 2
chdir("/cjo/docs/vertical/pub")         = 0
setitimer(ITIMER_PROF, {it_interval={0, 0}, it_value={18000, 0}}, NULL) = 0
fcntl(3, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1, l_len=1}) = 0
stat("/cjo/docs/vertical/pub/index.php", {st_mode=S_IFREG|0755, st_size=1246, ...}) = 0
lstat("/cjo/docs/vertical/pub/../app/bootstrap.php", {st_mode=S_IFREG|0755, st_size=2240, ...}) = 0
lstat("/cjo/docs/vertical/pub/../app", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/cjo/docs/vertical/app/bootstrap.php", {st_mode=S_IFREG|0755, st_size=2240, ...}) = 0
stat("/cjo/docs/vertical/app/autoload.php", {st_mode=S_IFREG|0755, st_size=1078, ...}) = 0
access("/cjo/docs/vertical/app/etc/vendor_path.php", F_OK) = 0
lstat("/cjo/docs/vertical/app/etc/vendor_path.php", {st_mode=S_IFREG|0755, st_size=70, ...}) = 0
lstat("/cjo/docs/vertical/app/etc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/cjo/docs/vertical/app", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/cjo/docs/vertical/app/etc/vendor_path.php", {st_mode=S_IFREG|0755, st_size=70, ...}) = 0
access("/cjo/docs/vertical/./vendor/autoload.php", F_OK) = 0

// 이 부분부터 핀포인트 있는 프로세스는 kill 된다.


lstat("/cjo/docs/vertical/./vendor/autoload.php", {st_mode=S_IFREG|0755, st_size=178, ...}) = 0
lstat("/cjo/docs/vertical/./vendor", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/cjo/docs/vertical/vendor/autoload.php", {st_mode=S_IFREG|0755, st_size=178, ...}) = 0
stat("/cjo/docs/vertical/vendor/composer/autoload_real.php", {st_mode=S_IFREG|0755, st_size=2591, ...}) = 0
lstat("/cjo/docs/vertical/vendor/composer/ClassLoader.php", {st_mode=S_IFREG|0755, st_size=13459, ...}) = 0

**Comment by sihouzhao** [comment]
Which version of your gcc is? OS ？

**Comment by lianfulei** [comment]
我也遇到此问题了
PHP 7.2.13 扩展了pinpoint.ini 就会出现502

**Comment by lianfulei** [comment]
所以我只能转向skywalking了

**Comment by eeliu** [comment]
@claytonxia @lianfulei  @sihouzhao @wasgosu 
Hi, if your php is php7.1+ , a better choice is upgrade to v0.2.0. It could be more stable and faster.
So, I closed this issue, if you found more, please create a new.

**Comment by lianfulei** [comment]
好的
