### ISSUE TITLE
Build Agent Error

### ISSUE THREAD

**Issue by DavenAaron** [naver/pinpoint-c-agent#71]
---------  with docker -------

FROM  php:7.2.16-fpm
LABEL maintainer="wangzenghui@juewei.com" app="nginx"
ENV DOC_ROOT  /var/www/html/

RUN apt-get update && apt-get install -y zlib1g-dev libcurl4-gnutls-dev autoconf libssl-dev git libtool automake libtool flex bison git

WORKDIR /usr/local/src/
RUN git clone http://github.com/naver/pinpoint-c-agent.git
RUN cd ./pinpoint-c-agent/pinpoint_php && ./Build.sh && make install

-------  errro message --------
/usr/local/src/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:77:3: note:   no known conversion for argument 1 from 'boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>' to 'std::shared_ptr<apache::thrift::transport::TTransport>'
/usr/local/src/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:36:7: note: candidate: apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>::TCompactProtocolT(const apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>&)
 class TCompactProtocolT : public TVirtualProtocol<TCompactProtocolT<Transport_> > {
       ^~~~~~~~~~~~~~~~~
/usr/local/src/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:36:7: note:   no known conversion for argument 1 from 'boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>' to 'const apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>&'
Makefile:129: recipe for target 'serializer.o' failed
make: *** [serializer.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by eeliu** [comment]
Pls check the thrift you used.

**Comment by ttraskback** [comment]
Facing the same issue

`
thrift 0.11.0

Building C (GLib) Library .... : no
Building C# (Mono) Library ... : no
Building C++ Library ......... : yes
Building D Library ........... : no
Building Dart Library ........ : no
Building dotnetcore Library .. : no
Building Erlang Library ...... : no
Building Go Library .......... : yes
Building Haskell Library ..... : no
Building Haxe Library ........ : no
Building Java Library ........ : no
Building Lua Library ......... : no
Building NodeJS Library ...... : no
Building Perl Library ........ : no
Building PHP Library ......... : no
Building Plugin Support ...... : no
Building Python Library ...... : no
Building Py3 Library ......... : yes
Building Ruby Library ........ : no
Building Rust Library ........ : no

C++ Library:
   C++ compiler .............. : g++
   Build TZlibTransport ...... : no
   Build TNonblockingServer .. : no
   Build TQTcpServer (Qt4) ... : no
   Build TQTcpServer (Qt5) ... : no
   C++ compiler version ...... : g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0

Go Library:
   Using Go................... : /usr/bin/go
   Using Go version........... : go version go1.10.4 linux/amd64

If something is missing that you think should be present,
please skim the output of configure to find the missing
component.  Details are present in config.log.
....
+ export WITH_BOOST_PATH=/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var
+ WITH_BOOST_PATH=/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var
+ export WITH_THRIFT_PATH=/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var
+ WITH_THRIFT_PATH=/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var
+ echo 'built common library ...'
built common library ...
+ '[' -z '' ']'
++ cat /proc/cpuinfo
++ grep processor
++ wc -l
+ export CPUNUM=8
+ CPUNUM=8
+ phpize -v
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
+ read_cmd
+ '[' NO = YES ']'
+ '[' NO = YES ']'
+ '[' NO = YES ']'
+ '[' NO = YES ']'
+ echo 'none gcov '
none gcov 
+ build_common
+ cd /home/totraskb/Documents/pinpoint-c-agent/pinpoint_common
+ make all -j8
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o thrift/gen-cpp/Trace_types.o thrift/gen-cpp/Trace_types.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o thrift/gen-cpp/Command_types.o thrift/gen-cpp/Command_types.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o thrift/gen-cpp/Pinpoint_types.o thrift/gen-cpp/Pinpoint_types.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o thrift/gen-cpp/Trace_constants.o thrift/gen-cpp/Trace_constants.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o thrift/gen-cpp/Command_constants.o thrift/gen-cpp/Command_constants.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o thrift/gen-cpp/Pinpoint_constants.o thrift/gen-cpp/Pinpoint_constants.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o pinpoint_agent.o pinpoint_agent.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o pinpoint_agent_context.o pinpoint_agent_context.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o log_utility.o log_utility.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o trace.o trace.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o utility.o utility.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o serializer.o serializer.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o executor.o executor.cpp
log_utility.cpp: In member function ‘void Pinpoint::log::LogUtility::outputLog(int32_t, const char*, int, const char*)’:
log_utility.cpp:240:90: error: argument to ‘sizeof’ in ‘char* strncpy(char*, const char*, size_t)’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
                     strncpy(fullLogBuf+(FORMAT_LOG_BUF_SIZE - sizeof(trun_str)),trun_str,sizeof(trun_str));
                                                                                          ^~~~~~~~~~~~~~~~
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o data_sender.o data_sender.cpp
g++ -c -fPIC -Wall   -O3 -DNDEBUG -Werror  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include  -isystem /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include   -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib  -L/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/lib -o buffer.o buffer.cpp
serializer.cpp: In constructor ‘Pinpoint::Agent::HeaderTBaseSerializer::HeaderTBaseSerializer()’:
serializer.cpp:117:103: error: no matching function for call to ‘apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>::TCompactProtocolT(boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>&)’
                 transportOut(new TMemoryBuffer()), protocolOut(new TCompactProtocol(this->transportOut))
                                                                                                       ^
In file included from serializer.h:24,
                 from serializer.cpp:18:
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:89:3: note: candidate: ‘apache::thrift::protocol::TCompactProtocolT<Transport_>::TCompactProtocolT(std::shared_ptr<_Tp>, int32_t, int32_t) [with Transport_ = apache::thrift::transport::TTransport; int32_t = int]’
   TCompactProtocolT(stdcxx::shared_ptr<Transport_> trans,
   ^~~~~~~~~~~~~~~~~
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:89:3: note:   candidate expects 3 arguments, 1 provided
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:77:3: note: candidate: ‘apache::thrift::protocol::TCompactProtocolT<Transport_>::TCompactProtocolT(std::shared_ptr<_Tp>) [with Transport_ = apache::thrift::transport::TTransport]’
   TCompactProtocolT(stdcxx::shared_ptr<Transport_> trans)
   ^~~~~~~~~~~~~~~~~
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:77:3: note:   no known conversion for argument 1 from ‘boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>’ to ‘std::shared_ptr<apache::thrift::transport::TTransport>’
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:36:7: note: candidate: ‘apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>::TCompactProtocolT(const apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>&)’
 class TCompactProtocolT : public TVirtualProtocol<TCompactProtocolT<Transport_> > {
       ^~~~~~~~~~~~~~~~~
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:36:7: note:   no known conversion for argument 1 from ‘boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>’ to ‘const apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>&’
serializer.cpp: In constructor ‘Pinpoint::Agent::HeaderTBaseDeSerializer::HeaderTBaseDeSerializer()’:
serializer.cpp:161:103: error: no matching function for call to ‘apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>::TCompactProtocolT(boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>&)’
                 transportOut(new TMemoryBuffer()), protocolOut(new TCompactProtocol(this->transportOut))
                                                                                                       ^
In file included from serializer.h:24,
                 from serializer.cpp:18:
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:89:3: note: candidate: ‘apache::thrift::protocol::TCompactProtocolT<Transport_>::TCompactProtocolT(std::shared_ptr<_Tp>, int32_t, int32_t) [with Transport_ = apache::thrift::transport::TTransport; int32_t = int]’
   TCompactProtocolT(stdcxx::shared_ptr<Transport_> trans,
   ^~~~~~~~~~~~~~~~~
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:89:3: note:   candidate expects 3 arguments, 1 provided
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:77:3: note: candidate: ‘apache::thrift::protocol::TCompactProtocolT<Transport_>::TCompactProtocolT(std::shared_ptr<_Tp>) [with Transport_ = apache::thrift::transport::TTransport]’
   TCompactProtocolT(stdcxx::shared_ptr<Transport_> trans)
   ^~~~~~~~~~~~~~~~~
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:77:3: note:   no known conversion for argument 1 from ‘boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>’ to ‘std::shared_ptr<apache::thrift::transport::TTransport>’
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:36:7: note: candidate: ‘apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>::TCompactProtocolT(const apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>&)’
 class TCompactProtocolT : public TVirtualProtocol<TCompactProtocolT<Transport_> > {
       ^~~~~~~~~~~~~~~~~
/home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include/thrift/protocol/TCompactProtocol.h:36:7: note:   no known conversion for argument 1 from ‘boost::shared_ptr<apache::thrift::transport::TMemoryBuffer>’ to ‘const apache::thrift::protocol::TCompactProtocolT<apache::thrift::transport::TTransport>&’
trace.cpp: In constructor ‘Pinpoint::Trace::CallStack::CallStack()’:
trace.cpp:745:25: error: catching polymorphic type ‘class std::bad_alloc’ by value [-Werror=catch-value=]
             catch (std::bad_alloc)
                         ^~~~~~~~~
make: *** [Makefile:129: serializer.o] Error 1
make: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make: *** [Makefile:129: log_utility.o] Error 1
cc1plus: all warnings being treated as errors
make: *** [Makefile:129: trace.o] Error 1
`

**Comment by eeliu** [comment]
It seems you thrift not right.

**Comment by ttraskback** [comment]
This is a clean clone of your repository where i ran the ./Build.sh script.

**Comment by ChenGXQQ** [comment]
Please check this path: /home/totraskb/Documents/pinpoint-c-agent/thirdparty/var/include
It seems that thrift is not installed correctly.

**Comment by ttraskback** [comment]
So this is what is in the thrift folder:
```
total 24
drwxr-xr-x   4 totraskb totraskb  4096 kesä   10 07:39 .
drwxr-xr-x   5 totraskb totraskb  4096 kesä   10 07:39 ..
drwxr-xr-x 112 totraskb totraskb 12288 kesä   10 07:35 boost
drwxr-xr-x   9 totraskb totraskb  4096 kesä   10 07:39 thrift
totraskb@IT-L-PF16LG50:~/Documents/pinpoint-c-agent/thirdparty/var/include$ cd thrift/
totraskb@IT-L-PF16LG50:~/Documents/pinpoint-c-agent/thirdparty/var/include/thrift$ ls -la
total 108
drwxr-xr-x 9 totraskb totraskb  4096 kesä   10 07:39 .
drwxr-xr-x 4 totraskb totraskb  4096 kesä   10 07:39 ..
drwxr-xr-x 2 totraskb totraskb  4096 kesä   10 07:39 async
drwxr-xr-x 2 totraskb totraskb  4096 kesä   10 07:39 concurrency
-rw-r--r-- 1 totraskb totraskb 13682 kesä   10 07:39 config.h
drwxr-xr-x 2 totraskb totraskb  4096 kesä   10 07:39 processor
drwxr-xr-x 2 totraskb totraskb  4096 kesä   10 07:39 protocol
drwxr-xr-x 2 totraskb totraskb  4096 kesä   10 07:39 qt
drwxr-xr-x 2 totraskb totraskb  4096 kesä   10 07:39 server
-rw-r--r-- 1 totraskb totraskb  4047 kesä   10 07:39 stdcxx.h
-rw-r--r-- 1 totraskb totraskb  3533 kesä   10 07:39 TApplicationException.h
-rw-r--r-- 1 totraskb totraskb  1190 kesä   10 07:39 TBase.h
-rw-r--r-- 1 totraskb totraskb  5167 kesä   10 07:39 TDispatchProcessor.h
-rw-r--r-- 1 totraskb totraskb   894 kesä   10 07:39 thrift-config.h
-rw-r--r-- 1 totraskb totraskb  3345 kesä   10 07:39 Thrift.h
-rw-r--r-- 1 totraskb totraskb 10429 kesä   10 07:39 TLogging.h
-rw-r--r-- 1 totraskb totraskb  1825 kesä   10 07:39 TOutput.h
-rw-r--r-- 1 totraskb totraskb  6803 kesä   10 07:39 TProcessor.h
drwxr-xr-x 2 totraskb totraskb  4096 kesä   10 07:39 transport
-rw-r--r-- 1 totraskb totraskb  3175 kesä   10 07:39 TToString.h
```

**Comment by eeliu** [comment]
v0.2.0 had released. It removed thrift dependency in module.
