### ISSUE TITLE
Pinpoint Php Agent for PHP 5.4 No Data

### ISSUE THREAD

**Issue by sihouzhao** [naver/pinpoint-c-agent#74]
pinpoint 1.8.2
PHP 5.4.41 (cli) (built: Jul  5 2017 04:26:31) 
centos 6.8
pinpoint-agent tag v0.1.1

config
[common]
AgentID=php
ApplicationName=php

## collector ip address

CollectorSpanIp=10.x.x.x
CollectorSpanPort=9996
CollectorStatIp=10.x.x.x
CollectorStatPort=9995
CollectorTcpIp=10.x.x.x
CollectorTcpPort=9994

TraceLimit = -1
SkipTraceTime = -1
# DEBUG|INFO|WARN|ERROR
PPLogLevel = DEBUG
LogFileRootPath = /opt/agent
# AgentType -> NGINX | APACHE |PHP |TEST
AgentType="PHP"

# plugin
# PhpInternalFunctionsPlugin
PluginExclude = ExcludePlugin
PluginInclude = PhpRequestPlugin;QuickStartPlugin  ; PhpInternalFunctionsPlugin ;ExcludePlugin ;PDOPlugin;CurlPlugin;

[PHP]
PluginEntryFile=plugins_create.php
PluginRootDir=/opt/pinpoint-c-agent/quickstart/php/web/plugins/

![image](https://user-images.githubusercontent.com/32085413/56201121-cd650a00-6072-11e9-9815-5ea7c473faf0.png)

**Comment by sihouzhao** [comment]
gcc version

**Comment by neatlife** [comment]
@sihouzhao how to fix this problem, I occur the same situation
