### ISSUE TITLE
The agent and php-fpm crash after a few requestes

### ISSUE THREAD

**Issue by levinzzp** [naver/pinpoint-c-agent#75]
Hi:
   I've met a wired problem.
   
   My Env:Nginx+PHP7.2+GCC4.7.4....Boost and Thrift are new version.
   After i build pinpoint.so successfully and config that into php.ini,it can be worked in a few requests,the request times same as number of php-fpm max-children,and the server create same numbers udp connection but not close,after that,my server will crash down.

    It seems like the server can't reuese  those udp connections so it can't load the classes in pinpoint_plugins.

    Can you help me to figure out this problem?

**Comment by ChenGXQQ** [comment]
I guess you turn on the multi-thread at PHP7. It is not available now and we are working hard to support it. If not, please show us the crash core file.

**Comment by eeliu** [comment]
hi， if you want to use zts within PHP7.1+. Try the v0.2.0, it supports multi-thread.
