### ISSUE TITLE
php7.0.14 no data in pinpoint web

### ISSUE THREAD

**Issue by neatlife** [naver/pinpoint-c-agent#80]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> hope data display on pinpoint-web

# Current Behavior

> no data in pinpoint-web

# Failure Information (for bugs)

no data, no error
![image](https://user-images.githubusercontent.com/4076198/58938338-303b6d80-87a7-11e9-910a-69058e7b7fda.png)

pinpoint log seems normal
![image](https://user-images.githubusercontent.com/4076198/58938398-4fd29600-87a7-11e9-8d9b-f20a25079f28.png)

## Steps to Reproduce

php 7.0.14
pinpoint 1.8.0
pinpoint-c-agent master
gcc: 4.8.5

```conf
[common]
AgentID=my_php_pinpoint
ApplicationName=PHPApplication

## collector ip address
CollectorSpanIp=10.x.x.x
CollectorSpanPort=9996
CollectorStatIp=10.x.x.x
CollectorStatPort=9995
CollectorTcpIp=10.x.x.x
CollectorTcpPort=9994

TraceLimit = -1
SkipTraceTime = -1
# DEBUG|INFO|WARN|ERROR
PPLogLevel = DEBUG
LogFileRootPath = /var/log/pinpoint/
# AgentType -> NGINX | APACHE |PHP |TEST
AgentType="PHP"

# plugin
# PhpInternalFunctionsPlugin
PluginExclude = ExcludePlugin
PluginInclude = PhpRequestPlugin ;QuickStartPlugin  ; PhpInternalFunctionsPlugin ;ExcludePlugin ;PDOPlugin;CurlPlugin;

[PHP]
PluginEntryFile=plugins_create.php
PluginRootDir=/pinpoint-c-agent/quickstart/php/web/plugins
;eg: PluginRootDir=/home/apps/php-7.1.0/pinpoint/web/php/plugins
```

**Comment by lianfulei** [comment]
在ini文件中

[pinpoint]
extension=/usr/lib/php/20170718/pinpoint.so
;trace_exception = true #agent will trace all excepiton
;trace_exception = false #agent ignore all the exception
pinpoint_agent.trace_exception=true
pinpoint_agent.config_full_name=/opt/app/pinpoint-c-agent/simulate/conf/pinpoint_agent.conf

按我的进行配置试试
;trace_exception = true #agent will trace all excepiton
;trace_exception = false #agent ignore all the exception
这2行不要开启

**Comment by neatlife** [comment]
@lianfulei 谢谢，问题是本地的项目连接云上的pinpoint好像有问题，我本地起个pinpoint就有数据了，云上的pinpoint的端口都开放了也收不到数据

**Comment by lianfulei** [comment]
pinpoint 对php支持不好，无法使用，已经转向skywalking了。

**Comment by lpvus** [comment]
@lianfulei php扩展有最新版了，你可以试试，我研究半天

**Comment by lianfulei** [comment]
好的
