### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nicedu123** [naver/pinpoint-c-agent#82]
make[3]: Leaving directory `/usr/local/pinpoint-c-agent/thirdparty/thrift/compiler/cpp'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/local/pinpoint-c-agent/thirdparty/thrift/compiler/cpp'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/pinpoint-c-agent/thirdparty/thrift'
make: *** [all] Error 2

**Comment by EyelynSu** [comment]
It seems thrift installed failed. 
You can try Option2. Install from source code.
