### ISSUE TITLE
centos 6.5 compile thrift failed

### ISSUE THREAD

**Issue by linuxmyjob** [naver/pinpoint-c-agent#90]
hello, it is all failed with the two option:1.Use agent build tools and Use agent build tools
when i  use option 2 the error is :

cc1plus: warning: unrecognized command line option "-Wno-c++11-long-long"
make[4]: *** [src/thrift/async/libthriftnb_la-TEvhttpServer.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
cc1plus: warning: unrecognized command line option "-Wno-c++11-long-long"
make[4]: *** [src/thrift/async/libthriftnb_la-TEvhttpClientChannel.lo] Error 1
libtool: compile: g++ -DHAVE_CONFIG_H -I. -I../.. -I../../lib/cpp/src/thrift -I../../lib/c_glib/src/thrift -I/web/pinpoint-c-agent/thirdparty/var/include -I./src -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -pedantic -g -O2 -Wno-variadic-macros -Wno-long-long -Wno-c++11-long-long -MT src/thrift/transport/libthriftz_la-TZlibTransport.lo -MD -MP -MF src/thrift/transport/.deps/libthriftz_la-TZlibTransport.Tpo -c src/thrift/transport/TZlibTransport.cpp -o src/thrift/transport/libthriftz_la-TZlibTransport.o >/dev/null 2>&1
mv -f src/thrift/transport/.deps/libthriftz_la-TZlibTransport.Tpo src/thrift/transport/.deps/libthriftz_la-TZlibTransport.Plo
make[4]: Leaving directory /web/pinpoint-c-agent/thirdparty/thrift/lib/cpp' make[3]: *** [all-recursive] Error 1 make[3]: Leaving directory /web/pinpoint-c-agent/thirdparty/thrift/lib/cpp'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory /web/pinpoint-c-agent/thirdparty/thrift/lib' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory /web/pinpoint-c-agent/thirdparty/thrift'
make: *** [all] Error 2

my environment  ：
os        CentOS release 6.10 (Final) and CentOS release 6.5 (Final)
pinpoint-c-agent v0.1.1
gcc*
libgcc-4.4.7-23.el6.x86_64
gcc-4.4.7-23.el6.x86_64
gcc-c++-4.4.7-23.el6.x86_64
gcc-gfortran-4.4.7-23.el6.x86_64

**Comment by eeliu** [comment]
@linuxmyjob 

We recommended you compiling thrift with more higher GCC( gcc.4.8+).

**Comment by eeliu** [comment]
@linuxmyjob

hi, does your PHP application support composer classloader?

**Comment by eeliu** [comment]
I closed it, as it looks done.
