### ISSUE TITLE
php 5.6.40 c-agent 502 error

### ISSUE THREAD

**Issue by iwzd520** [naver/pinpoint-c-agent#91]
# Prerequisites
- [ checked] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> Please describe the behavior you are expecting

# Current Behavior

> What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

**install step**
git clone https://github.com/naver/pinpoint-c-agent.git
yum install automake libtool flex bison pkgconfig gcc-c++ openssl-devel

wget https://dl.bintray.com/boostorg/release/1.63.0/source/boost_1_70_0.tar.gz
tar -zxvf boost_1_63_0.tar.gz && cd boost_1_63_0
./bootstrap.sh
./b2 install --prefix=/usr/local/boost

wget http://mirror.bit.edu.cn/apache/thrift/0.11.0/thrift-0.11.0.tar.gz
 tar zxvf thrift-0.11.0.tar.gz && cd thrift-0.11.0
./configure CXXFLAGS="-DFORCE_BOOST_SMART_PTR" --with-cpp --with-php=no --with-python=no --with-ruby=no --with-nodejs=no --with-qt4=no --with-java=no -with-boost=/usr/local/boost --prefix=/usr/local/thrift
make && make install

export WITH_BOOST_PATH=/usr/local/boost
export WITH_THRIFT_PATH=/usr/local/thrift
export LD_LIBRARY_PATH=/usr/local/boost/lib:/usr/local/bin/thrift:$LD_LIBRARY_PATH

cd pinpoint_php && ./Build.sh && sudo make install

Please provide detailed steps for reproducing the issue.

**1.**
when I systemctl restart php-fpm;
access my website ,it's 502 error code;
and I type php -m ,it,s show The following
_[root@localhost log]# php -m
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Aborted_

**2、**if I give a error PluginRootDir  (ex:PluginRootDir=/data/wwwroot/default/web/plugins111/),
it's seemed worked，and type php -m shows The following
_[root@localhost log]# php -m 
PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
PHP Warning:  Unknown: Failed opening '/data/wwwroot/default/web/plugins111/plugins_create.php' for inclusion (include_path='.:/usr/local/php/lib/php') in Unknown on line 0
[PHP Modules]
bcmath
……_

**and option 2 ，when i visit  pinpion-web,I can find the app data.**

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: CentOS 7.5
* GCC 👍 gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
* PHP Version:PHP 5.6.40 (cli) (built: Jul 21 2019 10:18:14)

* php.ini:
[php.ini.txt](https://github.com/naver/pinpoint-c-agent/files/3414290/php.ini.txt)

[pinpoint]
extension=/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/pinpoint.so
pinpoint_agent.trace_exception=true
pinpoint_agent.config_full_name=/etc/pinpoint_agent.conf
;eg:
;extension=/home/apps/php-7.1.0/modules/pinpoint/php-7.1.0-centos-6.x-release-pinpoint.so
;pinpoint_agent.config_full_name=/home/apps/php-7.1.0/pinpoint/conf/pinpoint_agent.conf

* php-fpm or apache:php-fpm

* pinpoint_agent.conf:
[common]
AgentID=php_pinpoint
ApplicationName=PHPApplication

CollectorSpanIp=192.168.8.208
CollectorSpanPort=9996
CollectorStatIp=192.168.8.208
CollectorStatPort=9995
CollectorTcpIp=192.168.8.208
CollectorTcpPort=9994

TraceLimit = -1
SkipTraceTime = -1
PPLogLevel = DEBUG
LogFileRootPath = /data/wwwlogs/
AgentType="PHP"

PluginExclude = ExcludePlugin
PluginInclude = PhpRequestPlugin;QuickStartPlugin  ; PhpInternalFunctionsPlugin ;ExcludePlugin ;PDOPlugin;CurlPlugin;

[PHP]
PluginEntryFile=plugins_create.php
PluginRootDir=/data/wwwroot/default/web/plugins/
;eg: PluginRootDir=/home/apps/php-7.1.0/pinpoint/web/php/plugins

## plugins
I used the dome web plugins.
pinpoint-c-agent/quickstart/php/web/plugins/*

## Failure Logs
[php-fpm.log](https://github.com/naver/pinpoint-c-agent/files/3414284/php-fpm.log)

[pinpoint_log.txt](https://github.com/naver/pinpoint-c-agent/files/3414285/pinpoint_log.txt)
[00-pinpiont.ini.txt](https://github.com/naver/pinpoint-c-agent/files/3414286/00-pinpiont.ini.txt)
[pinpoint_agent.conf.txt](https://github.com/naver/pinpoint-c-agent/files/3414287/pinpoint_agent.conf.txt)

**Comment by ChenGXQQ** [comment]
The program crashed. Unfortunately, we can not know why from these information you share. Firstly, please ensure that you don't turn on multi-thread. If the error still happens, please show us the core dump file and the plugins which you writes.

**Comment by iwzd520** [comment]
export WITH_BOOST_PATH=/usr/local/boost
export WITH_THRIFT_PATH=/usr/local/thrift
export LD_LIBRARY_PATH=/usr/local/boost/lib:_**/usr/local/thrift/bin/thrift**_:$LD_LIBRARY_PATH

I have a question.
The Italics  body（/usr/local/thrift/bin/thrift），Does it mean the BIN files?

**Comment by iwzd520** [comment]
some times ,i type php -m ,it's show fllowe

[root@web001 ~]# php -m
*** Error in `php': free(): invalid pointer: 0x00007fd7b8959768 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81489)[0x7fd7b371f489]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/ioncube_loader_lin_5.6.so(+0xdcd54)[0x7fd7ac307d54]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/ioncube_loader_lin_5.6.so(+0xd7b78)[0x7fd7ac302b78]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/ioncube_loader_lin_5.6.so(+0xd8e72)[0x7fd7ac303e72]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/ioncube_loader_lin_5.6.so(+0x73955)[0x7fd7ac29e955]
php(zend_execute_scripts+0xff)[0x87896f]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/pinpoint.so(+0xb92b0)[0x7fd7ab76f2b0]
/usr/local/php/lib/php/extensions/no-debug-non-zts-20131226/pinpoint.so(zm_activate_pinpoint+0x11a)[0x7fd7ab76e67a]
php(zend_activate_modules+0x30)[0x87e570]
php(php_request_startup+0x10a)[0x81592a]
php[0x91d555]
php[0x46f7bf]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fd7b36c03d5]
php[0x46f85a]
======= Memory map: ========
00400000-00e19000 r-xp 00000000 fd:00 1503687                            /usr/local/php/bin/php
01019000-010f1000 r--p 00a19000 fd:00 1503687                            /usr/local/php/bin/php
010f1000-01114000 rw-p 00af1000 fd:00 1503687                            /usr/local/php/bin/php
01114000-0113c000 rw-p 00000000 00:00 0 
02f21000-0378c000 rw-p 00000000 00:00 0                                  [heap]
7fd790000000-7fd790021000 rw-p 00000000 00:00 0 
7fd790021000-7fd794000000 ---p 00000000 00:00 0 
7fd79580d000-7fd7a180d000 rw-s 00000000 00:04 74425                      /dev/zero (deleted)
7fd7a180d000-7fd7a188d000 rw-s 00000000 00:04 557057                     /SYSV00000000 (deleted)
7fd7a188d000-7fd7a190e000 rw-p 00000000 00:00 0 
7fd7a190e000-7fd7a1b0f000 rw-s 00000000 00:04 74422                      /dev/zero (deleted)
7fd7a1b0f000-7fd7a1cc4000 r-xp 00000000 fd:00 35017                      /usr/lib64/libdb-5.3.so
7fd7a1cc4000-7fd7a1ec4000 ---p 001b5000 fd:00 35017                      /usr/lib64/libdb-5.3.so
7fd7a1ec4000-7fd7a1ecb000 r--p 001b5000 fd:00 35017                      /usr/lib64/libdb-5.3.so
7fd7a1ecb000-7fd7a1ece000 rw-p 001bc000 fd:00 35017                      /usr/lib64/libdb-5.3.so
7fd7a1ece000-7fd7a1ed4000 r-xp 00000000 fd:00 50333851                   /usr/lib64/sasl2/libsasldb.so.3.0.0
7fd7a1ed4000-7fd7a20d3000 ---p 00006000 fd:00 50333851                   /usr/lib64/sasl2/libsasldb.so.3.0.0
7fd7a20d3000-7fd7a20d4000 r--p 00005000 fd:00 50333851                   /usr/lib64/sasl2/libsasldb.so.3.0.0

**Comment by eeliu** [comment]
If you use php7.1+, we recommanded you upgrade to v0.2.0. It fix these "502"  problems with a new solutions.
As php 5.6 is end of its life, v0.2.0 not support it neither.
