### ISSUE TITLE
how dose the applications is interrelated?

### ISSUE THREAD

**Issue by linuxmyjob** [naver/pinpoint-c-agent#93]
hello,i have two applications in pinpoint,the name is devops and devops_229 . when i request http://qa.megatron.baidu-shucheng.com  it reached devops,and the devops will requests devops_229
for example:
![image](https://user-images.githubusercontent.com/8079815/61681855-ca4c7a80-ad41-11e9-8bf3-7078fd10e5cc.png)
![image](https://user-images.githubusercontent.com/8079815/61681915-01229080-ad42-11e9-8869-c56ab7918307.png)
the devops_229 is qa.megatron.baidu-shucheng.com ,how dose the devops_229 replaced the qa.megatron.baidu-shucheng.com,please help me

**Comment by ChenGXQQ** [comment]
You mean that devops sends http request to devops_229, right? So what http request lib do you use? if curl, you should turn on curl plugin. If others, you have to write you own plugin and the curl plugin we supply is a good example.

**Comment by linuxmyjob** [comment]
yes,devops sends http request to devops_229  and the request lib is also curl .But where should i turn on curl plugin

**Comment by ChenGXQQ** [comment]
Can you give us the whole start log? I want to ensure if CurlPlugin start successfully.

**Comment by ChenGXQQ** [comment]
![图片](https://user-images.githubusercontent.com/20234781/61923049-3246cf00-af95-11e9-9d9f-16ef8120a186.png)
And check this option at devops page. Inbound/Outbound > 1

**Comment by linuxmyjob** [comment]
hello,let me introduce our environment detailed:
cenos 6.5
nginx 1.10.2
php 5.6
the pinpoint_agent.conf:
[pinpoint_agent.conf.zip](https://github.com/naver/pinpoint-c-agent/files/3434783/pinpoint_agent.conf.zip)
the php.ini
[php.ini.zip](https://github.com/naver/pinpoint-c-agent/files/3434793/php.ini.zip)
[pinpoint_log_front_11.txt.zip](https://github.com/naver/pinpoint-c-agent/files/3434802/pinpoint_log_front_11.txt.zip)
[pinpoint_log_middle_229.txt.zip](https://github.com/naver/pinpoint-c-agent/files/3434808/pinpoint_log_middle_229.txt.zip)



i rename ApplicationName in the pinpoint_agent.con ,the devops is front_111 and the devops_229 is middle_229.

i request http://qa.megatron.baidu-shucheng.com the pinpoint Draw two picture like this :

the front_111 :
![image](https://user-images.githubusercontent.com/8079815/61936451-5cad8200-afbf-11e9-88e4-b126a0d8cdfb.png)
the middle_229
![image](https://user-images.githubusercontent.com/8079815/61936490-718a1580-afbf-11e9-9df3-d5dc65a0ee7e.png)
AND when i request http://qa.megatron.baidu-shucheng.com the front_111 send requests to qa.anduril.baidu-shucheng.com and the qa.anduril.baidu-shucheng.com is middle_229 so i thougt the two picuture should be associated with each other like this:
![image](https://user-images.githubusercontent.com/8079815/61938119-e9a60a80-afc2-11e9-974d-83de33454493.png)

**Comment by linuxmyjob** [comment]
hello,please help me

**Comment by eeliu** [comment]
> pinpoint_log_front_11.txt


```
send udp packet failed. e=send_to: Message too long, length=128371]
```

We commanded you removing some plugins not cared. The span is too big.

Like this : PluginInclude = PhpRequestPlugin;CurlPlugin; 

@linuxmyjob

**Comment by linuxmyjob** [comment]
@eeliu 
i altered it  and  there is no failed message,but i  also dose not work

**Comment by ChenGXQQ** [comment]
@linuxmyjob Can you get the HTTP header the middle_229 received?

**Comment by linuxmyjob** [comment]
@ChenGXQQ 
i can received the http header from middle_229 it like this:

![image](https://user-images.githubusercontent.com/8079815/62114457-4f5b0500-b2e9-11e9-8838-76b1a8efb0ca.png)
the host bdwx-szq2 is the middle_229

**Comment by ChenGXQQ** [comment]
@linuxmyjob I mean the detailed Http header. For server map, Pinpoint adds some Http header in your request. We want to check if it is right in your env.

**Comment by linuxmyjob** [comment]
@ChenGXQQ  the header is
![image](https://user-images.githubusercontent.com/8079815/62179571-98f62f00-b37f-11e9-8583-3e8959fc6641.png)

**Comment by ChenGXQQ** [comment]
@linuxmyjob The pinpoint headers are lost. But I don't know why. How does your applications use curl?
Pinpoint agent adds some http header when curl request. You can see the curl_plugin.php:
```
        if ($trace)
        {
            // event is Pinpoint\\SpanEventRecorder
            $event = $trace->traceBlockBegin($callId);
            $attachedHeader = array();
            $spanid = -1;
            if($trace->getNextSpanInfo($attachedHeader,$spanid))
            {
                $opt_header = array_merge($attachedHeader,$_SERVER[(string)$args[0]][CURLOPT_HTTPHEADER]);
                array_push($opt_header,'Pinpoint-Host:'.$_SERVER[(string)$args[0]][CURLOPT_URL]);
                curl_setopt($args[0], CURLOPT_HTTPHEADER,$opt_header);

                $event->setNextSpanId($spanid);
            }
            $event->addAnnotation(PINPOINT_ANNOTATION_ARGS+2,json_encode(curl_getinfo($args[0])));
            $event->markBeforeTime();
            $event->setApiId($this->apiId);
            $event->setServiceType(PINPOINT_PHP_REMOTE);
            $event->setDestinationId($_SERVER[(string)$args[0]][CURLOPT_URL]);
        }
```
And the http headers added are here:
```
    const char HTTP_TRACE_ID[] = "Pinpoint-TraceID";
    const char HTTP_SPAN_ID[] = "Pinpoint-SpanID";
    const char HTTP_PARENT_SPAN_ID[] = "Pinpoint-pSpanID";
    const char HTTP_SAMPLED[] = "Pinpoint-Sampled";
    const char HTTP_FLAGS[] = "Pinpoint-Flags";
    const char HTTP_PARENT_APPLICATION_NAME[] = "Pinpoint-pAppName";
    const char HTTP_PARENT_APPLICATION_TYPE[] = "Pinpoint-pAppType";
    const char HTTP_HOST[] = "Pinpoint-Host";
```

**Comment by linuxmyjob** [comment]
hello,i had find the problem which in the curl_plugin.php. it dose not set the heaer  CURLOPT_HTTPHEADER in our codes when request the qa.anduril.baidu-shucheng.com:8080,so the $_SERVER[(string)$args[0]][CURLOPT_HTTPHEADER] is empty and this code "$opt_header = array_merge($attachedHeader,$_SERVER[(string)$args[0]][CURLOPT_HTTPHEADER]);
                array_push($opt_header,'Pinpoint-Host:'.$_SERVER[(string)$args[0]][CURLOPT_URL]);
                curl_setopt($args[0], CURLOPT_HTTPHEADER,$opt_header);
" is failed . I alter the curl_plugin.php like this:

![image](https://user-images.githubusercontent.com/8079815/62524965-2696ba80-b869-11e9-8a4f-5d90126387dd.png)
i thought this shuld be a bug because the request  code do not set CURLOPT_HTTPHEADER sometimes.

**Comment by ChenGXQQ** [comment]
@linuxmyjob Thanks. You are right. It is a bug. We'll fix it ASAP. And if you want, you can create a pull request which should include testcase. We are welcome for your contribution.

**Comment by eeliu** [comment]
@linuxmyjob 
Please goto v0.1 branch.
