### ISSUE TITLE
Pinpoint cannot monitor multiple PHP projects on a single server

### ISSUE THREAD

**Issue by gebiwws** [naver/pinpoint-c-agent#94]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the [documentation](https://github.com/naver/pinpoint-c-agent/wiki),[issues](https://github.com/naver/pinpoint-c-agent/issues) and found no answer

# Expected Behavior

> Please describe the behavior you are expecting

# Current Behavior

> What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:

* PHP Version: 7.1

* php.ini:

* php-fpm or apache:
[phpini.zip](https://github.com/naver/pinpoint-c-agent/files/3492004/phpini.zip)
[pinpoint_log.tar.gz](https://github.com/naver/pinpoint-c-agent/files/3492005/pinpoint_log.tar.gz)

* pinpoint_agent.conf:

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )

**Comment by eeliu** [comment]
hmm， yes!
php-agent server node base on configuration. 
But your idea is great, thank you for your response.

**Comment by eeliu** [comment]
@gebiwws

[v0.2.1](https://github.com/naver/pinpoint-c-agent/releases/tag/v0.2.1) had supported  that. Please check that.
