### ISSUE TITLE
Third-party library display under user's namespace when print $who( variables in Plugin of Candy).

### ISSUE THREAD

**Issue by EyelynSu** [naver/pinpoint-c-agent#98]
[env]
pinpoint-c-agent: [dev-2](https://github.com/naver/pinpoint-c-agent/tree/dev-2)

[step]
1. Print variables $who in plugin which hook third-part library(PDO, Mysqli, Redis...): 
```
///@hook:app\DBcontrol::\PDO::prepare
class CommonPlugin extends Candy
{
    public function onBefore(){
        echo "onBefore <br>";
        ...
        echo "<br>who: ";
        var_dump($this->who);
        ...
    }
```

[result]
```PDO::prepare``` is under namespace ```app```.
```
app\PDO::prepare start 
onBefore 
unique:14232
args: array(1) { [0]=> string(42) "SELECT name FROM user where name='xiaogao'" } 
who: object(app\PDO)#8 (0) { } 
```

**Comment by eeliu** [comment]
@EyelynSu 

We use namespace alias to hook the built-in functions/method.
This is not a bug.
